import { EurekaZoneInfo } from './eureka';
import southHornMap from './southhorn.png';

// https://xivapi.com/search?indexes=Fate&filters=ID%3E=1717,ID%3C=1742&columns=Description,Name,Url

export const zoneInfoSouthHorn: EurekaZoneInfo = {
  mapImage: southHornMap,
  mapWidth: 2048,
  mapHeight: 2048,
  shortName: 'southhorn',
  hasTracker: false,
  onlyShowInactiveWithExplicitRespawns: true,
  treatNMsAsSkirmishes: true,
  mapToPixelXScalar: 50,
  mapToPixelXConstant: -50,
  mapToPixelYScalar: 50,
  mapToPixelYConstant: -50,
  fieldNotes: [
    {
      id: 8,
      name: {
        en: 'Trade Tortoise',
        de: 'Die Münzkröte',
        fr: 'Tortue à pièces',
        ja: 'コイントートス',
      },
      shortName: {
        en: 'Tortoise',
        de: 'Münzkröte',
        fr: 'Tortue',
        ja: 'トートス',
      },
      rarity: 0,
    },
    {
      id: 10,
      name: {
        en: 'Nymian Petalodus',
        de: 'Der nymeische Petalodus',
        fr: 'Petalodus de Nym',
        ja: 'ニーム・ペタロドゥス',
      },
      shortName: {
        en: 'Petalodus',
        de: 'Petalodus',
        fr: 'Petalodus',
        ja: 'ペタロドゥス',
      },
      rarity: 0,
    },
    {
      id: 11,
      name: {
        en: 'Persistent Pots',
        de: 'Der Wunderpott',
        fr: 'Pots persistants',
        ja: 'おねだりポット',
      },
      shortName: {
        en: 'Pots',
        de: 'Wunderpott',
        fr: 'Pots',
        ja: 'ポット',
      },
      rarity: 0,
    },
    {
      id: 14,
      name: {
        en: 'Mythic Idol',
        de: 'Das mystische Idol',
        fr: 'Idole mythique',
        ja: 'ミシカルアイドル',
      },
      shortName: {
        en: 'Idol',
        de: 'Idol',
        fr: 'Idole',
        ja: 'アイドル',
      },
      rarity: 0,
    },
    {
      id: 16,
      name: {
        en: 'Black Chocobos',
        de: 'Die schwarzen Chocobos',
        fr: 'Chocobos noirs',
        ja: '黒チョコボ',
      },
      shortName: {
        en: 'Chocobos',
        de: 'Chocobos',
        fr: 'Chocobos',
        ja: 'チョコボ',
      },
      rarity: 0,
    },
    {
      id: 17,
      name: {
        en: 'Crescent Berserker',
        de: 'Der kreszente Berserker',
        fr: 'Berserker de Lunule',
        ja: 'クレセント・バーサーカー',
      },
      shortName: {
        en: 'Berserker',
        de: 'Berserker',
        fr: 'Berserker',
        ja: 'バーサーカー',
      },
      rarity: 0,
    },
    {
      id: 20,
      name: {
        en: 'Cloister Demon',
        de: 'Der Klosterdämon',
        fr: 'Démon du Cloître',
        ja: 'クロイスターデーモン',
      },
      shortName: {
        en: 'Cloister',
        de: 'Klosterdämon',
        fr: 'Démon',
        ja: 'デーモン',
      },
      rarity: 0,
    },
  ],
  nms: {
    roughwaters: {
      label: {
        en: 'Rough Waters',
        de: 'Die Wogen glätten',
        fr: 'Pas de vagues',
        ja: '波起こしの海魔「ナンム」',
      },
      shortLabel: {
        en: 'Waters',
        de: 'Wogen',
        fr: 'Vagues',
        ja: 'ナンム',
      },
      x: 24.7,
      y: 35,
      fateId: 1962,
    },
    thegoldenguardian: {
      label: {
        en: 'The Golden Guardian',
        de: 'Brocken statt Barren',
        fr: 'Tombe vingt-quatre carats',
        ja: '金色の怪石「ゴールデンブロックス」',
      },
      shortLabel: {
        en: 'Guardian',
        de: 'Brocken',
        fr: 'Carats',
        ja: 'ゴールデンブロックス',
      },
      x: 28.9,
      y: 31.2,
      fateId: 1963,
    },
    kingofthecrescent: {
      label: {
        en: 'King of the Crescent',
        de: 'Geißel Kreszentias',
        fr: 'La bête sadique',
        ja: '悲鳴の蒐集者「ロプロス」',
      },
      shortLabel: {
        en: 'Crescent',
        de: 'Kreszentias',
        fr: 'Bête',
        ja: 'ロプロス',
      },
      x: 16.9,
      y: 26.5,
      fateId: 1964,
    },
    thewingedterror: {
      label: {
        en: 'The Winged Terror',
        de: 'Dämonenvogel am Spieß',
        fr: 'Je fus zu',
        ja: '甲板の掃除人「巨大鳥」',
      },
      shortLabel: {
        en: 'Terror',
        de: 'Dämonenvogel',
        fr: 'Fus',
        ja: '巨大鳥',
      },
      x: 10.5,
      y: 9.5,
      fateId: 1965,
    },
    anunendingduty: {
      label: {
        en: 'An Unending Duty',
        de: 'Los, Sisyphos, Donnerblitz!',
        fr: 'Pierre de tonnerre',
        ja: '神罰の石獣「シジフォス」',
      },
      shortLabel: {
        en: 'Duty',
        de: 'Donnerblitz',
        fr: 'Pierre',
        ja: 'シジフォス',
      },
      x: 17,
      y: 22.1,
      fateId: 1966,
    },
    braindrain: {
      label: {
        en: 'Brain Drain',
        de: 'Aspho ... asphy ... scheintot!',
        fr: 'Le poison de l\'évolution',
        ja: '進化せし怪蛇「アドバンスドエイビス」',
      },
      shortLabel: {
        en: 'Brain',
        de: 'Asphy',
        fr: 'Poison',
        ja: 'アドバンスドエイビス',
      },
      x: 20.5,
      y: 15,
      fateId: 1967,
    },
    adelicatebalance: {
      label: {
        en: 'A Delicate Balance',
        de: 'Kampf um Leben und Schweiß',
        fr: 'Humidité zéro',
        ja: '湿度の狩手「ディヒューミディファイア」',
      },
      shortLabel: {
        en: 'Balance',
        de: 'Schweiß',
        fr: 'Humidité',
        ja: 'ディヒューミディファイア',
      },
      x: 14,
      y: 34.4,
      fateId: 1968,
    },
    sworntosoil: {
      label: {
        en: 'Sworn to Soil',
        de: 'Kampf um Leben und Boden unter den Füßen',
        fr: 'Rester de boue',
        ja: '土壌の守り手「マッドマッド」',
      },
      shortLabel: {
        en: 'Soil',
        de: 'Boden',
        fr: 'Boue',
        ja: 'マッドマッド',
      },
      x: 9.7,
      y: 28.1,
      fateId: 1969,
    },
    apryingeye: {
      label: {
        en: 'A Prying Eye',
        de: 'Wächter des Lebens',
        fr: 'Un œil sur l\'île',
        ja: '監視の瞳「アイルオブザーバー」',
      },
      shortLabel: {
        en: 'Eye',
        de: 'Wächter',
        fr: 'Œil',
        ja: 'アイルオブザーバー',
      },
      x: 20,
      y: 32.6,
      fateId: 1970,
    },
    fatalallure: {
      label: {
        en: 'Fatal Allure',
        de: 'Tückische Schönheit',
        fr: 'La belle mort',
        ja: '美しき呪殺者「イグゼクレーター」',
      },
      shortLabel: {
        en: 'Allure',
        de: 'Schönheit',
        fr: 'Mort',
        ja: 'イグゼクレーター',
      },
      x: 23,
      y: 27,
      fateId: 1971,
    },
    servingdarkness: {
      label: {
        en: 'Serving Darkness',
        de: 'Seelen sammeln für den bösen Zweck',
        fr: 'Collecte mortelle',
        ja: '命の収奪者「ライフギャザラー」',
      },
      shortLabel: {
        en: 'Darkness',
        de: 'Seelen',
        fr: 'Collecte',
        ja: 'ライフギャザラー',
      },
      x: 29.7,
      y: 21.2,
      fateId: 1972,
    },
    persistentpots: {
      label: {
        en: 'Persistent Pots',
        de: 'Freude im Pott',
        fr: 'Pas de pot pour les pots',
        ja: 'しあわせのマジックポット',
      },
      fieldNotes: 11,
      shortLabel: {
        en: 'Pots',
        de: 'Pott',
        fr: 'Pots',
        ja: 'ポット',
      },
      x: 25.4,
      y: 17.1,
      bunny: true,
      fateId: 1976,
    },
    pleadingpots: {
      label: {
        en: 'Pleading Pots',
        de: 'Wunder im Pott',
        fr: 'Mauvais œil pour les pots',
        ja: 'カチカチのマジックポット',
      },
      fieldNotes: 11,
      shortLabel: {
        en: 'Pots',
        de: 'Pott',
        fr: 'Pots',
        ja: 'ポット',
      },
      x: 11.8,
      y: 32,
      bunny: true,
      fateId: 1977,
    },
    /* theforkedtowerblood: {
      label: {
        en: 'The Forked Tower: Blood',
        de: 'Der Turm des Blutes',
        fr: 'Tour fourchue de la Force',
        ja: 'フォークタワー：力の塔',
      },
      shortLabel: {
        en: 'Forked (Blood)',
        de: 'Turm (Blut)',
        fr: 'Tour (Force)',
        ja: '塔（力）',
      },
      x: 22.7,
      y: 21.6,
      isCritical: true,
      ceKey: 0,
    }, */
    scourgeofthemind: {
      label: {
        en: 'Scourge of the Mind',
        de: 'Die Geißel des Geistes',
        fr: 'L\'Encéphalophage',
        ja: '脳髄愛好家「マインドフレイア」',
      },
      shortLabel: {
        en: 'Scourge',
        de: 'Geißel',
        fr: 'Scourge',
        ja: 'マインド',
      },
      x: 27.4,
      y: 35.9,
      isCritical: true,
      ceKey: 1,
    },
    theblackregiment: {
      label: {
        en: 'The Black Regiment',
        de: 'Das schwarze Regiment',
        fr: 'Plumes d\'encre',
        ja: '黒の連隊',
      },
      fieldNotes: 16,
      shortLabel: {
        en: 'Regiment',
        de: 'Regiment',
        fr: 'Plumes',
        ja: '連隊',
      },
      x: 30.5,
      y: 28.6,
      isCritical: true,
      ceKey: 2,
    },
    theunbridled: {
      label: {
        en: 'The Unbridled',
        de: 'Zorn auf zwei Beinen',
        fr: 'Le Rageux',
        ja: '怒れる人造人間「クレセント・バーサーカー」',
      },
      fieldNotes: 17,
      shortLabel: {
        en: 'Unbridled',
        de: 'Zorn',
        fr: 'Rageux',
        ja: 'バーサーカー',
      },
      x: 33.8,
      y: 37.4,
      isCritical: true,
      ceKey: 3,
    },
    crawlingdeath: {
      label: {
        en: 'Crawling Death',
        de: 'Das messerscharfe Schicksal',
        fr: 'Face de griffes',
        ja: '忍び寄る爪「デスクロー」',
      },
      shortLabel: {
        en: 'Death',
        de: 'Schicksal',
        fr: 'Griffes',
        ja: 'デスクロー',
      },
      x: 35.0,
      y: 32.1,
      isCritical: true,
      ceKey: 4,
    },
    calamitybound: {
      label: {
        en: 'Calamity Bound',
        de: 'Das versiegelte Unheil',
        fr: 'Cloître à perpétuité',
        ja: '封印大妖「クロイスターデーモン」',
      },
      fieldNotes: 20,
      shortLabel: {
        en: 'Calamity',
        de: 'Unheil',
        fr: 'Cloître',
        ja: 'クロイスター',
      },
      x: 14.6,
      y: 37.4,
      isCritical: true,
      ceKey: 5,
    },
    trialbyclaw: {
      label: {
        en: 'Trial by Claw',
        de: 'Tödliche Schönheit',
        fr: 'Écailles de cristal',
        ja: '模造されしもの「水晶竜」',
      },
      shortLabel: {
        en: 'Claw',
        de: 'Schönheit',
        fr: 'Cristal',
        ja: '水晶竜',
      },
      x: 13.2,
      y: 22.9,
      isCritical: true,
      ceKey: 6,
    },
    fromtimesbygone: {
      label: {
        en: 'From Times Bygone',
        de: 'Von uralten Magien',
        fr: 'Idole surprise',
        ja: '神秘の偶像「ミシカルアイドル」',
      },
      fieldNotes: 14,
      shortLabel: {
        en: 'Bygone',
        de: 'Magien',
        fr: 'Idole',
        ja: 'アイドル',
      },
      x: 5.5,
      y: 26.4,
      isCritical: true,
      ceKey: 7,
    },
    companyofstone: {
      label: {
        en: 'Company of Stone',
        de: 'Die steinerne Staffel',
        fr: 'L\'Armée des argileux',
        ja: '石造りの守護騎士たち',
      },
      shortLabel: {
        en: 'Stone',
        de: 'Stein',
        fr: 'Argileux',
        ja: '守護騎士',
      },
      x: 35.1,
      y: 16.2,
      isCritical: true,
      ceKey: 8,
    },
    sharkattack: {
      label: {
        en: 'Shark Attack',
        de: 'Jäger aus alten Legenden',
        fr: 'Homo selachus',
        ja: '伝説の鮫「ニーム・ペタロドゥス」',
      },
      fieldNotes: 10,
      shortLabel: {
        en: 'Shark',
        de: 'Jäger',
        fr: 'Shark',
        ja: 'ペタロドゥス',
      },
      x: 19.1,
      y: 4.4,
      isCritical: true,
      ceKey: 9,
    },
    onthehunt: {
      label: {
        en: 'On the Hunt',
        de: 'Gefürchtetes Gebrüll',
        fr: 'À rugir debout',
        ja: '二足の獅子「ランパントライオン」',
      },
      shortLabel: {
        en: 'Hunt',
        de: 'Gebrüll',
        fr: 'Lion',
        ja: 'ライオン',
      },
      x: 34.0,
      y: 20.0,
      isCritical: true,
      ceKey: 10,
    },
    withextremeprejudice: {
      label: {
        en: 'With Extreme Prejudice',
        de: 'Mit absoluter Sicherheit',
        fr: 'Cordon de sécurité',
        ja: 'セキュリティ・コマンドー',
      },
      shortLabel: {
        en: 'Prejudice',
        de: 'Sicherheit',
        fr: 'Sécurité',
        ja: 'コマンドー',
      },
      x: 14.4,
      y: 9.3,
      isCritical: true,
      ceKey: 11,
    },
    noisecomplaint: {
      label: {
        en: 'Noise Complaint',
        de: 'Keine Gnade dem Gefieder',
        fr: 'Mammouth fâché',
        ja: '鳥嫌いの巨獣「ネオガルラ」',
      },
      shortLabel: {
        en: 'Complaint',
        de: 'Gefieder',
        fr: 'Mammouth',
        ja: 'ガルラ',
      },
      x: 30.5,
      y: 14.1,
      isCritical: true,
      ceKey: 12,
    },
    cursedconcern: {
      label: {
        en: 'Cursed Concern',
        de: 'Das Feilschen ums Verfluchte',
        fr: 'Être aux pièces',
        ja: '呪いの商亀「コイントートス」',
      },
      fieldNotes: 8,
      shortLabel: {
        en: 'Concern',
        de: 'Verfluchte',
        fr: 'Pièces',
        ja: 'トートス',
      },
      x: 22.9,
      y: 10.6,
      isCritical: true,
      ceKey: 13,
    },
    eternalwatch: {
      label: {
        en: 'Eternal Watch',
        de: 'Ausgebessert und verbessert',
        fr: 'Comme un lion nouveau',
        ja: '復元された獅子像「リペアドライオン」',
      },
      shortLabel: {
        en: 'Watch',
        de: 'Wacht',
        fr: 'Lion',
        ja: 'ライオン',
      },
      x: 38.9,
      y: 25.1,
      isCritical: true,
      ceKey: 14,
    },
    flameofdusk: {
      label: {
        en: 'Flame of Dusk',
        de: 'Das finsterste Feuer',
        fr: 'Les ailes de pierre',
        ja: '昏き篝火「ヒンキーパンク」',
      },
      shortLabel: {
        en: 'Dusk',
        de: 'Feuer',
        fr: 'Pierre',
        ja: 'ヒンキー',
      },
      x: 10.1,
      y: 18.3,
      isCritical: true,
      ceKey: 15,
    },
  },
};
