import NetRegexes from '../../../../../resources/netregexes';
import ZoneId from '../../../../../resources/zone_id';
import { OopsyData } from '../../../../../types/data';
import { OopsyTriggerSet } from '../../../../../types/oopsy';
import { kFlagInstantDeath, playerDamageFields } from '../../../oopsy_common';

// TODO: 63DD Skyward Leap during Strength of the Heavens should ignore invulning tanks
// TODO: track missing towers during 니드호그

export interface Data extends OopsyData {
  towerAbility?: string;
  convictionTower?: { [name: string]: boolean };
  hasDoom?: { [name: string]: boolean };
}

const triggerSet: OopsyTriggerSet<Data> = {
  zoneId: ZoneId.DragonsongsRepriseUltimate,
  damageWarn: {
    'DSR 그리노 도넛 /임티 디멘전': '62DA', // donut (phase1 and Wrath)
    'DSR 그리노 장판 /풀 디멘전': '62DB', // circle (phase 1)
    'DSR 아델펠 줄 /홀리 실드 배시': '63EB', // line charge at tethered player
    'DSR 아델펠 돌진 /샤이닝 블레이드': '62CE', // dash attack
    'DSR Brightsphere Bright Flare': '62CF', // spheres generated by 62CE Shining Blade
    'DSR 샤리벨 장판 /스카이블라인드': '631A', // puddles after Brightwing cleaves
    'DSR 돌진 /스파이럴 스러스트': '63D4', // dashes from Ser Vellguine, Ser Ignasse, Ser Paulecrain
    'DSR 게릭 지진 1': '63D6', // expanding earth ring
    'DSR 게릭 지진 2': '63D7', // expanding earth ring
    'DSR 게릭 지진 3': '63D8', // expanding earth ring
    'DSR 게릭 지진 4': '63D9', // expanding earth ring
    'DSR 게릭 지진 5': '63DA', // expanding earth ring
    'DSR 그리노 빨강검정 장판': '63DC', // red/black puddles
    'DSR 샤리벨 성장 불장판x4': '6FAF', // initial Sanctity of the Ward 4x fire puddles
    'DSR 샤리벨 성장 도넛링': '6FB0', // Sanctity of the Ward donut ring before fire/ice
    'DSR 또르탕 휘두르기x3': '63C2', // 3x directional cleaves
    'DSR 니드호그 그내시/밖으로': '6715', // "get out" part of Gnash and Lash
    'DSR 니드호그 내시/안으로': '6716', // "get in" part of Gnash and Lash
    'DSR 니드호그 게이른스코른': '670A', // baited line aoes from tower clones
    'DSR 니드호그 드라첸랜스': '670C', // front conal
    'DSR 비도프닐 트위스터 다이브': '6B8B', // initial dragon dive + twister during Wrath/Death
    'DSR 샤리벨 알터 플레어': '63E4', // 4x big explosions during Wrath of the Heavens
    'DSR 비도프닐 카탈라이즈': '6B8E', // dive during Wrath/Death
    'DSR 다크스케일 카탈라이즈': '6B8D', // dive during Wrath/Death
    'DSR 다크스케일 체인 라이트닝': '6B90', // 2x lightning spread during Wrath (doesn't hit player it's on)
    'DSR 제피랑 스피어 오브 더 퓨리': '6B93', // spear line aoe during Death of the Heavens
    'DSR 다크스케일 윙 오브 살베이션': '6B96', // white puddle that creates doom cleanser in Death of the Heavens
  },
  damageFail: {
    'DSR 줄 연결 /디멘전 토르션': '62D8', // player tethering a cloud
    'DSR 줄 연결 /디멘전 퍼게이션': '62D9', // 아델펠 tethering a cloud during charges
    'DSR 샤리벨 홀리 체인': '62E0', // failing to break chains, often kills people
    'DSR 그리노 플래너 프리즌': '63EC', // leaving the purple circle
    'DSR 운석이 가깝네 / 홀리xx': '63EA', // meteor explosion from being too close
    'DSR 또르탕 아스칼론 메르시 컨실드': '63C9', // protean 2nd hit
    'DSR 니드호그 타워 실패 /다크드래곤 다이브': '671B', // tower failure
  },
  gainsEffectFail: {
    'DSR 번': 'B81', // fire puddles during Sanctity of the Ward
    'DSR 프로스트 바이트': 'B82', // ice puddles during Sanctity of the Ward
  },
  shareWarn: {
    'DSR 아델펠 Execution': '62D5', // dive on main tank after 62CE Shining Blade
    'DSR 샤리벨 Heavensflame': '62DF', // spread with 62E0 Holy Chain (also in Death)
    'DSR 샤리벨 Brightwing': '6319', // cleaves during Pure of Heart
    'DSR 또르탕 Attack': '63BB', // 또르탕 cleave autos
    'DSR 또르탕 Lightning Storm': '63CD', // spread during Strength of the Ward
    'DSR 니드호그 Attack': '6730', // 니드호그 cleave autos
    'DSR 니드호그 Dark High Jump': '670E', // sharing a circle marker tower drop
    'DSR 니드호그 Dark Spineshatter Dive': '670F', // sharing an up/forwards arrow marker tower drop
    'DSR 니드호그 Dark Elusive Jump': '6710', // sharing a down/back arrow marker tower drop
    'DSR 니드호그 Darkdragon Dive Share': '6711', // sharing a single tower
    'DSR Spiral Pierce': '6B8A', // Ser Ignasse and Ser Vellguine tether charges during Wrath
    'DSR 또르탕 Ascalon\'s Mercy Revealed': '63CB', // protean during Wrath
  },
  shareFail: {
    'DSR 또르탕 아스칼론 마이트': '63C5', // tank cleaves
    'DSR 홀리 실드 배시': '62D1', // 아델펠/Janlenoux tank tether stun charges
    'DSR 니드호그 소울 테터': '671C', // tank tether cleaves
    'DSR 니드호그 미라지 다이브': '68C4', // dives during eye phase, probably a wipe if shared
    'DSR Skyward Leap 1x': '72A2', // Ser Paulecraine single blue marker during Wrath
  },
  soloWarn: {
    'DSR 오메릭 Hiemal Storm': '63E7', // Sanctity of the Ward ice pair stacks
  },
  triggers: [
    {
      // Interrupt.
      id: 'DSR Ser Adelphel Holiest Hallowing',
      type: 'Ability',
      netRegex: NetRegexes.ability({ id: '62D0' }),
      mistake: (_data, matches) => {
        return { type: 'fail', blame: matches.target, text: matches.ability };
      },
    },
    {
      id: 'DSR Ser Hermenost Conviction Cast Cleanup',
      type: 'StartsUsing',
      // 63DE/63DF = Strength of the Ward towers
      // 737B/737C = Sanctity of the Ward first towers
      // 6FEA/6FEB = Sanctity of the Ward second towers
      netRegex: NetRegexes.startsUsing({ id: ['63DE', '737B', '6FEA'] }),
      run: (data, matches) => {
        data.towerAbility = matches.id;
        data.convictionTower = {};
      },
    },
    {
      id: 'DSR Ser Hermenost Conviction Tower Collect',
      type: 'Ability',
      netRegex: NetRegexes.ability({ id: ['63DF', '737C', '6FEB'], ...playerDamageFields }),
      run: (data, matches) => (data.convictionTower ??= {})[matches.target] = true,
    },
    {
      id: 'DSR Ser Hermenost Eternal Conviction Failure',
      type: 'Ability',
      netRegex: NetRegexes.ability({ id: '63E0' }),
      suppressSeconds: 1,
      mistake: (data) => {
        const missing = data.party.partyNames.filter((name) => {
          if (data.convictionTower?.[name])
            return false;
          // Skip tanks on Conviction during Strength of the Ward.
          if (data.towerAbility === '63DE' && data.party.isTank(name))
            return false;
          return true;
        }).sort();
        return missing.map((name) => {
          return {
            type: 'fail',
            blame: name,
            text: {
              en: '타워 실패',
            },
          };
        });
      },
    },
    {
      id: 'DSR Ser Adelphel Holiest Hallowing',
      type: 'Ability',
      netRegex: NetRegexes.ability({ id: '62D0' }),
      mistake: (_data, matches) => {
        return { type: 'fail', blame: matches.target, text: matches.ability };
      },
    },
    {
      id: 'DSR King Thordan Gaze',
      // Same abilities during both Thordan1 and Thordan2
      // 63D1 = The Dragon's Gaze (Thordan lookaway)
      // 63D2 = The Dragon's Glory (eye lookaway)
      // Technically there is also a Hysteria status (127) but sometimes this doesn't apply (if somebody dies too soon??).
      type: 'Ability',
      netRegex: NetRegexes.ability({ id: ['63D1', '63D2'], ...playerDamageFields }),
      condition: (data, matches) => data.DamageFromMatches(matches) > 0,
      mistake: (_data, matches) => {
        return { type: 'fail', blame: matches.target, reportId: matches.targetId, text: matches.ability };
      },
    },
    {
      id: 'DSR King Thordan Twister',
      type: 'Ability',
      netRegex: NetRegexes.ability({ id: '6B8C', ...playerDamageFields }),
      mistake: (_data, matches) => {
        // Instant death has a special flag value, differentiating
        // from the explosion damage you take when somebody else
        // pops one.
        if (matches.flags === kFlagInstantDeath) {
          return {
            type: 'fail',
            blame: matches.target,
            reportId: matches.targetId,
            text: {
              en: '트위스터 실패',
              de: 'Wirbelsturm berührt',
              fr: 'Apparition des tornades',
              ja: 'ツイスター',
              cn: '旋风',
              ko: '회오리 밟음',
            },
          };
        }
        // If not the one popping, just print "Twister".
        return {
          type: 'fail',
          blame: matches.target,
          reportId: matches.targetId,
          text: matches.ability,
        };
      },
    },
    {
      id: 'DSR Doom Gain',
      type: 'GainsEffect',
      netRegex: NetRegexes.gainsEffect({ effectId: 'BA0' }),
      run: (data, matches) => (data.hasDoom ??= {})[matches.target] = true,
    },
    {
      id: 'DSR Doom Lose',
      type: 'LosesEffect',
      netRegex: NetRegexes.losesEffect({ effectId: 'BA0' }),
      run: (data, matches) => (data.hasDoom ??= {})[matches.target] = false,
    },
    {
      // There is no trigger line for when doom runs out, so check slightly
      // before to see if doom was cleared or if we should consider any
      // non-damage death after this a doom.
      id: 'DSR Doom Death',
      type: 'GainsEffect',
      netRegex: NetRegexes.gainsEffect({ effectId: 'BA0' }),
      delaySeconds: (_data, matches) => parseFloat(matches.duration) - 0.5,
      deathReason: (data, matches) => {
        if (!data.hasDoom || !data.hasDoom[matches.target])
          return;
        return {
          id: matches.targetId,
          name: matches.target,
          text: matches.effect,
        };
      },
    },
  ],
};

export default triggerSet;
