// Auto-generated from gen_ce_info_and_maps.ts
// DO NOT EDIT THIS FILE DIRECTLY

import { CeInfoType } from '../types/ce';

const data: CeInfoType = {
  'AcesHigh': {
    'directorId': '1D2',
    'name': {
      'de': 'Gabriel, die stählerne Schwinge',
      'en': 'Aces High',
      'fr': 'Force divine',
      'ja': '新型飛行型魔導アーマー「ガブリエル」',
    },
  },
  'AndTheFlamesWentHigher': {
    'directorId': '1D3',
    'name': {
      'de': 'Sartauvoir Eisenfeuer',
      'en': 'And the Flames Went Higher',
      'fr': 'L\'envol du phénix',
      'ja': '老練の魔道士「鉄火のサルトヴォアール」',
    },
  },
  'BeastOfMan': {
    'directorId': '1DB',
    'name': {
      'de': 'Lyon der Bestienkönig',
      'en': 'Beast of Man',
      'fr': 'Le Roi bestial',
      'ja': '百獣使い「獣王ライアン」',
    },
  },
  'KillItWithFire': {
    'directorId': '1D4',
    'name': {
      'de': 'Peeriefool, das faule Gemüse',
      'en': 'Kill It with Fire',
      'fr': 'Grandeur et pestilence',
      'ja': '腐乱野菜「ピーリフール」',
    },
  },
  'MetalFoxChaos': {
    'directorId': '1CB',
    'name': {
      'de': 'Dáinsleif, Bestie aus Eisen',
      'en': 'Metal Fox Chaos',
      'fr': 'Le guerrier de métal',
      'ja': '鋼鉄の魔獣「ダーインスレイヴ」',
    },
  },
  'PatriotGames': {
    'directorId': '1D1',
    'name': {
      'de': 'Verteidigungsmaschine Patriot',
      'en': 'Patriot Games',
      'fr': 'Les fusils du patriote',
      'ja': '拠点防衛魔導兵器「パトリオット」',
    },
  },
  'RiseOfTheRobots': {
    'directorId': '1DF',
    'name': {
      'de': 'Im Schatten von Modell X',
      'en': 'Rise of the Robots',
      'fr': 'Le soulèvement des machines',
      'ja': '新たなる鉄巨人「魔導レイバーX型」',
    },
  },
  'TheBattleOfCastrumLacusLitore': {
    'directorId': '1D7',
    'name': {
      'de': 'Sturm auf Castrum Lacus Litore',
      'en': 'The Battle of Castrum Lacus Litore',
      'fr': 'Assaut sur Castrum Lacus Litore',
      'ja': 'カストルム・ラクスリトレ攻城戦',
    },
  },
  'TheBayingOfTheHounds': {
    'directorId': '1CC',
    'name': {
      'de': 'Die drei Mäuler des Canis dirus',
      'en': 'The Baying of the Hound(s)',
      'fr': 'Le chien des enfers',
      'ja': '戦争の妖犬「カニスディルス」',
    },
  },
  'TheFinalFurlong': {
    'directorId': '1D5',
    'name': {
      'de': 'Spartoi der Gefürchtete',
      'en': 'The Final Furlong',
      'fr': 'Menace spectrale',
      'ja': '怨念の死霊「スパルトイ」',
    },
  },
  'TheFiresOfWar': {
    'directorId': '1D6',
    'name': {
      'de': 'Die Flammenden Hundert',
      'en': 'The Fires of War',
      'fr': 'Brasier de guerre',
      'ja': '炎獣使い「火焔百人隊」',
    },
  },
  'TheHuntForRedChoctober': {
    'directorId': '1CA',
    'name': {
      'de': 'Der Rote Meteor und seine Meute',
      'en': 'The Hunt for Red Choctober',
      'fr': 'Une ruée en rouge',
      'ja': '赤チョコボのヌシ「レッドコメット」',
    },
  },
  'TheShadowOfDeathsHand': {
    'directorId': '1CD',
    'name': {
      'de': 'Akbaba, Tod von oben',
      'en': 'The Shadow of Death\'s Hand',
      'fr': 'Les ailes noires de la mort',
      'ja': '黒き死鳥「アクババ」',
    },
  },
  'TrampledUnderHoof': {
    'directorId': '1CE',
    'name': {
      'de': 'Die bösen Blicke der Eale',
      'en': 'Trampled under Hoof',
      'fr': 'L\'œil du malin',
      'ja': '邪眼の妖獣「エアレー」',
    },
  },
  'VigilForTheLost': {
    'directorId': '1D0',
    'name': {
      'de': 'Vigil, Feuerkraft hoch zehn',
      'en': 'Vigil for the Lost',
      'fr': 'Vigile de feu',
      'ja': '高火力陸戦魔導兵器「ヴィジル」',
    },
  },
  'WhereStrodeTheBehemoth': {
    'directorId': '1DC',
    'name': {
      'de': 'Der untote Chlevnik',
      'en': 'Where Strode the Behemoth',
      'fr': 'Le mastodonte enragé',
      'ja': '戦慄の角「チルヴニク」',
    },
  },
} as const;

export default data;
