// Auto-generated from gen_ce_info_and_maps.ts
// DO NOT EDIT THIS FILE DIRECTLY

import { CeInfoType } from '../types/ce';

const data: CeInfoType = {
  'CalamityBound': {
    'directorId': '32F',
    'name': {
      'de': 'Das versiegelte Unheil',
      'en': 'Calamity Bound',
      'fr': 'Défi : Cloître à perpétuité',
      'ja': '封印大妖「クロイスターデーモン」',
    },
  },
  'CompanyOfStone': {
    'directorId': '343',
    'name': {
      'de': 'Die steinerne Staffel',
      'en': 'Company of Stone',
      'fr': 'L\'armée des argileux',
      'ja': '石造りの守護騎士たち',
    },
  },
  'CrawlingDeath': {
    'directorId': '330',
    'name': {
      'de': 'Das messerscharfe Schicksal',
      'en': 'Crawling Death',
      'fr': 'Défi : face de griffes',
      'ja': '忍び寄る爪「デスクロー」',
    },
  },
  'CursedConcern': {
    'directorId': '32B',
    'name': {
      'de': 'Das Feilschen ums Verfluchte',
      'en': 'Cursed Concern',
      'fr': 'Défi : être aux pièces',
      'ja': '呪いの商亀「コイントートス」',
    },
  },
  'EternalWatch': {
    'directorId': '329',
    'name': {
      'de': 'Ausgebessert und verbessert',
      'en': 'Eternal Watch',
      'fr': 'Défi : comme un lion nouveau',
      'ja': '復元された獅子像「リペアドライオン」',
    },
  },
  'FlameOfDusk': {
    'directorId': '32A',
    'name': {
      'de': 'Das finsterste Feuer',
      'en': 'Flame of Dusk',
      'fr': 'Défi : les ailes de pierre',
      'ja': '昏き篝火「ヒンキーパンク」',
    },
  },
  'FromTimesBygone': {
    'directorId': '323',
    'name': {
      'de': 'Von uralten Magien',
      'en': 'From Times Bygone',
      'fr': 'Défi : idole surprise',
      'ja': '神秘の偶像「ミシカルアイドル」',
    },
  },
  'NoiseComplaint': {
    'directorId': '327',
    'name': {
      'de': 'Keine Gnade dem Gefieder',
      'en': 'Noise Complaint',
      'fr': 'Défi : mammouth fâché',
      'ja': '鳥嫌いの巨獣「ネオガルラ」',
    },
  },
  'OnTheHunt': {
    'directorId': '338',
    'name': {
      'de': 'Gefürchtetes Gebrüll',
      'en': 'On the Hunt',
      'fr': 'Défi : à rugir debout',
      'ja': '二足の獅子「ランパントライオン」',
    },
  },
  'ScourgeOfTheMind': {
    'directorId': '320',
    'name': {
      'de': 'Die Geißel des Geistes',
      'en': 'Scourge of the Mind',
      'fr': 'Défi : l\'encéphalophage',
      'ja': '脳髄愛好家「マインドフレイア」',
    },
  },
  'SharkAttack': {
    'directorId': '32E',
    'name': {
      'de': 'Jäger aus alten Legenden',
      'en': 'Shark Attack',
      'fr': 'Défi : homo selachus',
      'ja': '伝説の鮫「ニーム・ペタロドゥス」',
    },
  },
  'TheBlackRegiment': {
    'directorId': '322',
    'name': {
      'de': 'Das schwarze Regiment',
      'en': 'The Black Regiment',
      'fr': 'Plumes d\'encre',
      'ja': '黒の連隊',
    },
  },
  'TheForkedTowerBlood': {
    'directorId': '33B',
    'name': {
      'de': 'Der Turm des Blutes',
      'en': 'The Forked Tower: Blood',
      'fr': 'Tour fourchue de la Force',
      'ja': 'フォークタワー：力の塔',
    },
  },
  'TheUnbridled': {
    'directorId': '348',
    'name': {
      'de': 'Zorn auf zwei Beinen',
      'en': 'The Unbridled',
      'fr': 'Défi : le rageux',
      'ja': '怒れる人造人間「クレセント・バーサーカー」',
    },
  },
  'TrialByClaw': {
    'directorId': '349',
    'name': {
      'de': 'Tödliche Schönheit',
      'en': 'Trial by Claw',
      'fr': 'Défi : écailles de cristal',
      'ja': '模造されしもの「水晶竜」',
    },
  },
  'WithExtremePrejudice': {
    'directorId': '339',
    'name': {
      'de': 'Mit absoluter Sicherheit',
      'en': 'With Extreme Prejudice',
      'fr': 'Cordon de sécurité',
      'ja': 'セキュリティ・コマンドー',
    },
  },
} as const;

export default data;
