// Auto-generated from gen_ce_info_and_maps.ts
// DO NOT EDIT THIS FILE DIRECTLY

import { CeInfoType } from '../types/ce';

const data: CeInfoType = {
  'AFamiliarFace': {
    'directorId': '212',
    'name': {
      'de': 'Hashmallim der Einiger',
      'en': 'A Familiar Face',
      'fr': 'Le Grand Ordonnateur',
      'ja': '模造統制者「IVレギオン・ハシュマリム」',
    },
  },
  'FeelingTheBurn': {
    'directorId': '20E',
    'name': {
      'de': 'Schwarzbrands Testflug',
      'en': 'Feeling the Burn',
      'fr': 'On arrête le progrès',
      'ja': '試作飛行型魔導アーマー「ブラックバーン」',
    },
  },
  'FromBeyondTheGrave': {
    'directorId': '21B',
    'name': {
      'de': 'Shemhazai der Verräter',
      'en': 'From Beyond the Grave',
      'fr': 'Le Sycophante',
      'ja': '模造密告者「IVレギオン・シュミハザ」',
    },
  },
  'HeadOfTheSnake': {
    'directorId': '21E',
    'name': {
      'de': 'Menenius, Tribunus der IV. Legion',
      'en': 'Head of the Snake',
      'fr': 'Mener par l\'exemple',
      'ja': '第IV軍団分遣隊長「メネニウス」',
    },
  },
  'HereComesTheCavalry': {
    'directorId': '21C',
    'name': {
      'de': 'Halb Pferd, halb Garlear',
      'en': 'Here Comes the Cavalry',
      'fr': 'Un cavalier qui surgit hors de la nuit',
      'ja': '鋼鉄の人馬「魔導騎兵大隊」',
    },
  },
  'LeanMeanMagitekMachines': {
    'directorId': '218',
    'name': {
      'de': 'Die Gepanzerte Zenturie',
      'en': 'Lean, Mean, Magitek Machines',
      'fr': 'Réusinage de code',
      'ja': '新兵器投入「機甲百人隊」',
    },
  },
  'LooksToDieFor': {
    'directorId': '207',
    'name': {
      'de': 'Regenbogenschlange Ayida',
      'en': 'Looks to Die For',
      'fr': 'Écaillage en règle',
      'ja': '輝ける虹蛇「アイダ」',
    },
  },
  'NeverCryWolf': {
    'directorId': '20F',
    'name': {
      'de': 'Eiswolf Hrodvitnir',
      'en': 'Never Cry Wolf',
      'fr': 'Et n\'y Hród\'viens plus !',
      'ja': '邪悪なる氷狼「フローズヴィトニル」',
    },
  },
  'OnSerpentsWings': {
    'directorId': '211',
    'name': {
      'de': 'Der Geistertrupp',
      'en': 'On Serpents\' Wings',
      'fr': 'Zirnitrop',
      'ja': '妖霊使い「妖戦百人隊」',
    },
  },
  'TakingTheLyonsShare': {
    'directorId': '220',
    'name': {
      'de': 'Revanche: Lyon der Bestienkönig',
      'en': 'Taking the Lyon\'s Share',
      'fr': 'La revanche de Lyon',
      'ja': '戦慄の百獣使い「獣王ライアン」',
    },
  },
  'TheBrokenBlade': {
    'directorId': '21F',
    'name': {
      'de': 'Hyper-Dabog, Stärkster unter Stärksten',
      'en': 'The Broken Blade',
      'fr': 'Dabog l\'hyper-renforcé',
      'ja': '非業の強化兵「ハイパーチューンド・ダボグ」',
    },
  },
  'TheDalriada': {
    'directorId': '213',
    'name': {
      'de': 'Sturm auf die Dalriada',
      'en': 'The Dalriada',
      'fr': 'Assaut sur le Dalriada',
      'ja': '旗艦ダル･リアータ攻略戦',
    },
  },
  'ThereWouldBeBlood': {
    'directorId': '210',
    'name': {
      'de': 'Hanbi, König im Exil',
      'en': 'There Would Be Blood',
      'fr': 'Le Roi des cendres',
      'ja': '異界の廃王「ハンビ」',
    },
  },
  'TimeToBurn': {
    'directorId': '21D',
    'name': {
      'de': 'Dämonid Belias',
      'en': 'Time to Burn',
      'fr': 'Le Titan',
      'ja': '模造魔人「IVレギオン・ベリアス」',
    },
  },
  'WithDiremiteAndMain': {
    'directorId': '221',
    'name': {
      'de': 'Hedetet, Stachel des Karglands',
      'en': 'With Diremite and Main',
      'fr': 'C\'est dans ma nature',
      'ja': '焦土の魔蠍「ヘデテト」',
    },
  },
  'WornToAShadow': {
    'directorId': '222',
    'name': {
      'de': 'Alkonost, schrecklich und gefiedert',
      'en': 'Worn to a Shadow',
      'fr': 'Oiseau d\'enfer',
      'ja': '有角の凶鳥「アルコノスト」',
    },
  },
} as const;

export default data;
