// This file was autogenerated from running ts-node util/sync_files.ts.
// DO NOT EDIT THIS FILE DIRECTLY.

import Conditions from '../../../../../resources/conditions';
import Outputs from '../../../../../resources/outputs';
import { Responses } from '../../../../../resources/responses';
import ZoneId from '../../../../../resources/zone_id';
import { RaidbossData } from '../../../../../types/data';
import { PluginCombatantState } from '../../../../../types/event';
import { NetMatches } from '../../../../../types/net_matches';
import { PartyMemberParamObject } from '../../../../../types/party';
import { Output, TriggerSet } from '../../../../../types/trigger';

type ClockRotate = 'cw' | 'ccw' | 'unknown';
type MarchDirection = 'front' | 'back' | 'left' | 'right' | 'unknown';

const ForceMoveStrings = {
  stack: Outputs.getTogether,
  spread: Outputs.spread,
  forward: {
    en: '강제이동: 앞 🡺 ${aim}',
  },
  backward: {
    en: '강제이동: 뒤 🡺 ${aim}',
  },
  left: {
    en: '강제이동: 왼쪽 🡺 ${aim}',
  },
  right: {
    en: '강제이동: 오른쪽 🡺 ${aim}',
  },
  move: {
    en: '강제이동 🡺 ${aim}',
  },
  safety: {
    en: '안전한 곳',
  },
} as const;

export interface Data extends RaidbossData {
  ketuCrystalAdd: NetMatches['AddedCombatant'][];
  ketuSpringCrystalCount: number;
  ketuHydroCount: number;
  ketuHydroStack?: NetMatches['GainsEffect'];
  ketuHydroSpread?: NetMatches['GainsEffect'];
  ketuEffectId?: string;
  lalaBlight: MarchDirection;
  lalaRotate: ClockRotate;
  lalaCount: number;
  lalaSubtractive: number;
  lalaMyMarch: MarchDirection;
  lalaMyRotate: ClockRotate;
  lalaMyCount: number;
  stcReloadCount: number;
  stcReloadFailed: number;
  stcRingRing: number;
  stcBullsEyes: PartyMemberParamObject[];
  stcClaws: string[];
  stcMissiles: string[];
  stcSeenPinwheeling: boolean;
  stcAdjustBullsEye: boolean;
  stcTether: boolean;
  stcChains: string[];
  stcBallFire?: number;
  stcPop: number;
  stcMyMarch: MarchDirection;
  stcMyDuration: number;
  gainList: NetMatches['GainsEffect'][];
  isStackFirst: boolean;
  //
  readonly triggerSetConfig: {
    stackOrder: 'meleeRolesPartners' | 'rolesPartners';
  };
  combatantData: PluginCombatantState[];
}

// Horizontal crystals have a heading of 0, vertical crystals are -pi/2.
const isHorizontalCrystal = (line: NetMatches['AddedCombatant']) => {
  const epsilon = 0.1;
  return Math.abs(parseFloat(line.heading)) < epsilon;
};

// 스택 먼저?
const isStackFirst = (
  stack?: NetMatches['GainsEffect'],
  spread?: NetMatches['GainsEffect'],
): boolean => {
  if (stack === undefined)
    return false;
  const stackTime = parseFloat(stack.duration);
  if (spread === undefined)
    return true;
  const spreadTime = parseFloat(spread.duration);
  return stackTime < spreadTime;
};

// 리버스?
const isReverseRotate = (rot: ClockRotate, count: number): boolean => {
  if (rot === 'cw' && count === 3)
    return true;
  if (rot === 'ccw' && (count === 0 || count === 5))
    return true;
  return false;
};

// 스타티스 나눔
const stcBallOfFire = (combatant: NetMatches['AddedCombatant']): number => {
  const hg = parseFloat(combatant.heading);
  return (Math.round(6 - 6 * (2 * Math.PI - hg) / Math.PI) % 12 + 12) % 12;
};

// 주사위를 마커로
const diceToMarker = (no: number): string => {
  const diceMap: { [dice: number]: string } = {
    1: 'Ⓐ',
    2: '①',
    3: '②',
    4: 'Ⓒ',
    5: '③',
    6: '④',
  } as const;
  const ret = diceMap[no];
  return ret === undefined ? '몰?루' : ret;
};

// 강제 이동
const forceMove = (
  output: Output,
  march: MarchDirection,
  stackFirst?: boolean,
  safezone?: string,
): string => {
  if (march !== undefined) {
    const move = {
      'front': output.forward,
      'back': output.backward,
      'left': output.left,
      'right': output.right,
      'unknown': output.move,
    }[march];
    if (safezone !== undefined)
      return move!({ aim: safezone });
    return move!({ aim: stackFirst ? output.stack!() : output.spread!() });
  }
  if (safezone !== undefined)
    return safezone;
  if (stackFirst)
    return output.stack!();
  return output.spread!();
};

const triggerSet: TriggerSet<Data> = {
  id: 'AnotherAloaloIslandSavage',
  zoneId: ZoneId.AnotherAloaloIslandSavage,
  timelineFile: 'another_aloalo_island-savage.txt',
  initData: () => {
    return {
      ketuCrystalAdd: [],
      ketuSpringCrystalCount: 0,
      ketuHydroCount: 0,
      lalaBlight: 'unknown',
      lalaRotate: 'unknown',
      lalaCount: 0,
      lalaSubtractive: 0,
      lalaMyMarch: 'unknown',
      lalaMyRotate: 'unknown',
      lalaMyCount: 0,
      stcReloadCount: 0,
      stcReloadFailed: 0,
      stcRingRing: 0,
      stcBullsEyes: [],
      stcClaws: [],
      stcMissiles: [],
      stcSeenPinwheeling: false,
      stcAdjustBullsEye: false,
      stcTether: false,
      stcChains: [],
      stcPop: 0,
      stcMyMarch: 'unknown',
      stcMyDuration: 0,
      gainList: [],
      isStackFirst: false,
      //
      combatantData: [],
    };
  },
  triggers: [
    // ---------------- first trash ----------------
    {
      id: 'AAIS Kiwakin Lead Hook',
      type: 'StartsUsing',
      netRegex: { id: '8BC7', source: 'Aloalo Kiwakin' },
      response: (data, matches, output) => {
        // cactbot-builtin-response
        output.responseOutputStrings = {
          tankBusterOnYou: {
            en: '내게 3연속 탱크버스터',
          },
          tankBusterOnPlayer: {
            en: '3연속 탱크버스터: ${player}',
          },
        };

        if (matches.target === data.me)
          return { alertText: output.tankBusterOnYou!() };
        const target = data.party.member(matches.target);
        return { infoText: output.tankBusterOnPlayer!({ player: target }) };
      },
    },
    {
      id: 'AAIS Kiwakin Sharp Strike',
      type: 'StartsUsing',
      netRegex: { id: '8BC8', source: 'Aloalo Kiwakin' },
      response: Responses.tankBuster(),
    },
    {
      id: 'AAIS Kiwakin Tail Screw',
      type: 'StartsUsing',
      // This is a baited targeted circle.
      netRegex: { id: '8BC9', source: 'Aloalo Kiwakin', capture: false },
      response: Responses.moveAway(),
    },
    {
      id: 'AAIS Snipper Water III',
      type: 'StartsUsing',
      netRegex: { id: '8BCC', source: 'Aloalo Snipper' },
      response: Responses.stackMarkerOn(),
    },
    {
      id: 'AAIS Snipper Bubble Shower',
      type: 'StartsUsing',
      netRegex: { id: '8BCA', source: 'Aloalo Snipper', capture: false },
      infoText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: '옆으로 (앞=>뒤 공격)',
      },
    },
    {
      id: 'AAIS Snipper Crab Dribble',
      type: 'Ability',
      // Crab Dribble 8BCB has a fast cast, so trigger on Bubble Shower ability
      netRegex: { id: '8BCA', source: 'Aloalo Snipper', capture: false },
      response: Responses.goFront('info'),
    },
    {
      id: 'AAIS Ray Hydrocannon',
      type: 'StartsUsing',
      netRegex: { id: '8C4B', source: 'Aloalo Ray', capture: false },
      response: Responses.getBehind(),
    },
    {
      id: 'AAIS Ray Expulsion',
      type: 'StartsUsing',
      netRegex: { id: '8BCE', source: 'Aloalo Ray', capture: false },
      response: Responses.getOut(),
    },
    {
      id: 'AAIS Ray Electric Whorl',
      type: 'StartsUsing',
      netRegex: { id: '8BCD', source: 'Aloalo Ray', capture: false },
      response: Responses.getUnder('alert'),
    },
    {
      id: 'AAIS Monk Hydroshot',
      type: 'StartsUsing',
      netRegex: { id: '8BD1', source: 'Aloalo Monk' },
      condition: Conditions.targetIsYou(),
      response: Responses.knockbackOn(),
    },
    {
      id: 'AAIS Monk Cross Attack',
      type: 'StartsUsing',
      netRegex: { id: '8C4F', source: 'Aloalo Monk' },
      response: Responses.tankBuster(),
    },
    // ---------------- Ketuduke ----------------
    {
      id: 'AAIS Ketuduke Tidal Roar',
      type: 'StartsUsing',
      netRegex: { id: '8AD4', source: 'Ketuduke', capture: false },
      response: Responses.bleedAoe(),
    },
    {
      id: 'AAIS Ketuduke Bubble Net',
      type: 'StartsUsing',
      netRegex: { id: '8AAD', source: 'Ketuduke', capture: false },
      response: Responses.aoe(),
    },
    {
      id: 'AAIS Ketuduke Spring Crystals',
      type: 'StartsUsing',
      netRegex: { id: '8AA8', source: 'Ketuduke', capture: false },
      run: (data) => {
        data.ketuSpringCrystalCount++;
        data.ketuCrystalAdd = [];
      },
    },
    {
      id: 'AAIS Ketuduke Spring Crystal 1 Collect',
      type: 'AddedCombatant',
      netRegex: { npcNameId: '12606' }, // 동글
      run: (data, matches) => data.ketuCrystalAdd.push(matches),
    },
    {
      id: 'AAIS Ketuduke Spring Crystal 2 Collect',
      type: 'AddedCombatant',
      netRegex: { npcNameId: '12607' }, // 네모
      run: (data, matches) => data.ketuCrystalAdd.push(matches),
    },
    {
      id: 'AAIS Ketuduke Bubble Weave/Foamy Fetters',
      type: 'GainsEffect',
      netRegex: { effectId: ['E9F', 'ECC'] },
      infoText: (data, matches, output) => {
        if (data.me !== matches.target)
          return;
        data.ketuEffectId = matches.effectId;
        if (matches.effectId === 'E9F')
          return output.bubble!();
        return output.bind!();
      },
      run: (data, matches) => data.gainList.push(matches),
      outputStrings: {
        bubble: '🔵버블',
        bind: '🟡바인드',
      },
    },
    {
      id: 'AAIS Ketuduke Hydrofall Target',
      type: 'GainsEffect',
      netRegex: { effectId: 'EA3' },
      run: (data, matches) => data.ketuHydroStack = matches,
    },
    {
      id: 'AAIS Ketuduke Hydrobullet Target',
      type: 'GainsEffect',
      netRegex: { effectId: 'EA4' },
      run: (data, matches) => data.ketuHydroSpread = matches,
    },
    {
      id: 'AAIS Ketuduke Fluke Gale Hydro',
      type: 'GainsEffect',
      netRegex: { effectId: ['EA3', 'EA4'] },
      condition: (data) => data.ketuHydroCount === 0 || data.ketuHydroCount === 5,
      delaySeconds: 0.5,
      suppressSeconds: 2,
      infoText: (_data, matches, output) => {
        if (matches.effectId === 'EA3')
          return output.stack!();
        return output.spread!();
      },
      run: (data) => data.ketuHydroCount++,
      outputStrings: {
        spread: Outputs.spread,
        stack: Outputs.pairStack,
      },
    },
    {
      id: 'AAIS Ketuduke Fluke Gale',
      type: 'Ability',
      netRegex: { id: '8AB1', source: 'Ketuduke', capture: false },
      durationSeconds: 8,
      alertText: (data, _matches, output) => {
        data.isStackFirst = isStackFirst(data.ketuHydroStack, data.ketuHydroSpread);
        if (data.ketuEffectId !== 'E9F' && !data.isStackFirst)
          return output.go2!();
        return output.go1!();
      },
      run: (data) => delete data.ketuEffectId,
      outputStrings: {
        go1: {
          en: '1번 칸으로',
        },
        go2: {
          en: '2번 칸으로',
        },
      },
    },
    {
      id: 'AAIS Ketuduke Blowing Bubbles',
      type: 'GainsEffect',
      netRegex: { effectId: ['EA3', 'EA4'], capture: false },
      condition: (data) => data.ketuHydroCount === 1,
      delaySeconds: 4,
      durationSeconds: 8,
      suppressSeconds: 999999,
      alertText: (data, _matches, output) => {
        data.isStackFirst = isStackFirst(data.ketuHydroStack, data.ketuHydroSpread);
        return data.isStackFirst ? output.stacks!() : output.spread!();
      },
      run: (data) => data.ketuHydroCount = 2,
      outputStrings: {
        stacks: {
          en: '뭉쳤다 => 흩어져요',
        },
        spread: {
          en: '흩어졌다 => 뭉쳐요',
        },
      },
    },
    {
      id: 'AAIS Ketuduke Blowing Bubbles Stack Reminder',
      type: 'GainsEffect',
      netRegex: { effectId: 'EA3' },
      condition: (data) => data.ketuHydroCount === 1,
      delaySeconds: (_data, matches) => parseFloat(matches.duration) - 5,
      suppressSeconds: 999999,
      alertText: (data, _matches, output) => {
        if (!data.isStackFirst)
          return output.pairStack!();
      },
      outputStrings: {
        pairStack: Outputs.pairStack,
      },
    },
    {
      id: 'AAIS Ketuduke Blowing Bubbles Spread Reminder',
      type: 'GainsEffect',
      netRegex: { effectId: 'EA4' },
      condition: (data) => data.ketuHydroCount === 1,
      delaySeconds: (_data, matches) => parseFloat(matches.duration) - 5,
      suppressSeconds: 999999,
      alertText: (data, _matches, output) => {
        if (data.isStackFirst)
          return output.spread!();
      },
      outputStrings: {
        spread: Outputs.spread,
      },
    },
    {
      id: 'AAIS Ketuduke Twintides Hydrofall Target',
      type: 'GainsEffect',
      netRegex: { effectId: 'EA3', capture: false },
      condition: (data) => data.ketuHydroCount === 2,
      run: (data) => {
        data.ketuHydroCount = 3;
        data.gainList = []; // Roar용 사람 찾기 리셋
      },
    },
    {
      id: 'AAIS Ketuduke Receding Twintides',
      type: 'StartsUsing',
      netRegex: { id: '8AE7', source: 'Ketuduke', capture: false },
      alertText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: '밖에 있다 => 안에서 페어',
        },
      },
    },
    {
      id: 'AAIS Ketuduke Encroaching Twintides',
      type: 'StartsUsing',
      netRegex: { id: '8AE9', source: 'Ketuduke', capture: false },
      alertText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: '안에 있다 => 밖에서 페어',
        },
      },
    },
    {
      id: 'AAIS Ketuduke Spring Crystals 2',
      type: 'AddedCombatant',
      netRegex: { npcNameId: '12607', capture: false },
      condition: (data) => data.ketuSpringCrystalCount === 2 && data.ketuCrystalAdd.length === 4,
      alertText: (data, _matches, output) => {
        const horizontal = data.ketuCrystalAdd.filter((x) => isHorizontalCrystal(x));
        const vertical = data.ketuCrystalAdd.filter((x) => !isHorizontalCrystal(x));
        if (horizontal.length !== 2 || vertical.length !== 2)
          return;

        // Crystal positions are always -15, -5, 5, 15.

        // Check if any verticals are on the outer vertical edges.
        for (const line of vertical) {
          const y = parseFloat(line.y);
          if (y < -10 || y > 10)
            return output.eastWestSafe!();
        }

        // Check if any horizontals are on the outer horizontal edges.
        for (const line of horizontal) {
          const x = parseFloat(line.x);
          if (x < -10 || x > 10)
            return output.northSouthSafe!();
        }

        return output.cornersSafe!();
      },
      outputStrings: {
        northSouthSafe: {
          en: '안전: 남북',
        },
        eastWestSafe: {
          en: '안전: 동서',
        },
        cornersSafe: {
          en: '안전: 모서리',
        },
      },
    },
    {
      id: 'AAIS Ketuduke Roar Search',
      type: 'GainsEffect',
      netRegex: { effectId: 'EA4' },
      condition: (data) => data.ketuHydroCount === 3,
      delaySeconds: (_data, matches) => parseFloat(matches.duration) - 10,
      durationSeconds: 8,
      suppressSeconds: 999999,
      alertText: (data, _matches, output) => {
        const [player] = data.gainList.filter((x) =>
          x.effectId === data.ketuEffectId && x.target !== data.me
        ).map((x) => data.party.member(x.target).ajob);
        if (data.ketuEffectId === 'E9F')
          return output.bubble!({ player: player });
        return output.bind!({ player: player });
      },
      run: (data) => {
        delete data.ketuEffectId;
        data.ketuHydroCount = 4;
        data.gainList = [];
      },
      outputStrings: {
        bubble: '바닥 쫄(${player}) => 자기 자리로',
        bind: '버블(${player}) => 자기 자리로',
      },
    },
    {
      id: 'AAIS Ketuduke Roar Move',
      type: 'StartsUsing',
      netRegex: { id: '8ADC', source: 'Spring Crystal', capture: false },
      condition: (data) => data.ketuHydroCount === 4, // 3이 아닐껄
      suppressSeconds: 2,
      alertText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: '쫄 뒤로!',
        },
      },
    },
    {
      id: 'AAIS Ketuduke Angry Seas Hydro',
      type: 'GainsEffect',
      netRegex: { effectId: ['EA3', 'EA4'], capture: false },
      condition: (data) => data.ketuHydroCount === 4,
      delaySeconds: 4.5,
      suppressSeconds: 999999,
      alertText: (data, _matches, output) => {
        data.isStackFirst = isStackFirst(data.ketuHydroStack, data.ketuHydroSpread);
        return data.isStackFirst ? output.stack!() : output.spread!();
      },
      run: (data) => data.ketuHydroCount = 5,
      outputStrings: {
        stack: {
          en: '뭉쳤다 => 흩어져요',
        },
        spread: {
          en: '흩어졌다 => 뭉쳐요',
        },
      },
    },
    {
      id: 'AAIS Ketuduke Angry Seas',
      type: 'StartsUsing',
      netRegex: { id: '8AE1', source: 'Ketuduke', capture: false },
      alertText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: '넉백! 저항하라!!!',
        },
      },
    },
    {
      id: 'AAIS Ketuduke Fluke Typhoon Bubble',
      type: 'StartsUsing',
      netRegex: { id: '8AAF', source: 'Ketuduke', capture: false },
      condition: (data) => data.role === 'dps',
      infoText: (data, _matches, output) => {
        if (data.ketuCrystalAdd.length !== 4 || data.ketuCrystalAdd[0] === undefined)
          return output.text!();
        if (parseFloat(data.ketuCrystalAdd[0].x) < 0)
          return output.left!();
        return output.right!();
      },
      run: (data) => data.ketuCrystalAdd = [],
      outputStrings: {
        text: '(슬슬 버블 타야 함)',
        left: '(왼쪽 DPS가 버블 타야 함)',
        right: '(오른쪽 DPS가 버블 타야 함)',
      },
    },
    {
      id: 'AAIS Ketuduke Fluke Typhoon Tower',
      type: 'Ability',
      netRegex: { id: '8AB0', source: 'Ketuduke', capture: false },
      suppressSeconds: 5,
      alertText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: '장판 피하면서 타워 밟아요',
        },
      },
    },
    // ---------------- second trash ----------------
    {
      id: 'AAIS Wood Golem Ancient Aero III',
      type: 'StartsUsing',
      netRegex: { id: '8C4C', source: 'Aloalo Wood Golem' },
      response: Responses.interruptIfPossible(),
    },
    {
      id: 'AAIS Wood Golem Tornado',
      type: 'StartsUsing',
      netRegex: { id: '8BD3', source: 'Aloalo Wood Golem' },
      infoText: (data, matches, output) => {
        if (data.me === matches.target)
          return output.itsme!();
        return output.text!({ player: data.party.member(matches.target).ajob });
      },
      outputStrings: {
        itsme: '내게 토네이도',
        text: '토네이도: ${player}',
      },
    },
    {
      id: 'AAIS Wood Golem Tornado Esuna',
      type: 'Ability',
      netRegex: { id: '8BD3', source: 'Aloalo Wood Golem' },
      condition: (data) => data.role === 'healer' || data.job === 'BRD',
      alertText: (data, matches, output) =>
        output.text!({ player: data.party.member(matches.target).ajob }),
      outputStrings: {
        text: '에스나: ${player}',
      },
    },
    {
      id: 'AAIS Wood Golem Ovation',
      type: 'StartsUsing',
      netRegex: { id: '8BD4', source: 'Aloalo Wood Golem', capture: false },
      infoText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: '옆이나 뒤로',
      },
    },
    {
      id: 'AAIS Islekeeper Ancient Quaga',
      type: 'StartsUsing',
      netRegex: { id: '8C39', source: 'Aloalo Islekeeper', capture: false },
      response: Responses.bleedAoe(),
    },
    {
      id: 'AAIS Islekeeper Gravity Force',
      type: 'StartsUsing',
      netRegex: { id: '8C3A', source: 'Aloalo Islekeeper' },
      infoText: (data, matches, output) => {
        if (data.me === matches.target)
          return output.itsme!();
        return output.text!({ player: data.party.member(matches.target).ajob });
      },
      outputStrings: {
        itsme: '내게 중력, 모여있다가',
        text: '중력, 모여있다가 (${player})',
      },
    },
    {
      id: 'AAIS Islekeeper Isle Drop',
      type: 'StartsUsing',
      netRegex: { id: '8C3C', source: 'Aloalo Islekeeper', capture: false },
      response: Responses.moveAway('alert'),
    },
    // ---------------- lala ----------------
    {
      id: 'AAIS Lala Inferno Theorem',
      type: 'StartsUsing',
      netRegex: { id: '8C05', source: 'Lala', capture: false },
      response: Responses.aoe(),
    },
    {
      id: 'AAIS Lala Lala 회전',
      type: 'HeadMarker',
      netRegex: { id: ['01E4', '01E5'], target: 'Lala' },
      run: (data, matches) => data.lalaRotate = matches.id === '01E4' ? 'cw' : 'ccw',
    },
    {
      id: 'AAIS Lala Lala 3과5',
      type: 'GainsEffect',
      // F62 = Times Three
      // F63 = Times Five
      netRegex: { effectId: ['F62', 'F63'], source: 'Lala', target: 'Lala' },
      run: (data, matches) => data.lalaCount = matches.effectId === 'F62' ? 3 : 5,
    },
    {
      id: 'AAIS Lala Player 회전',
      type: 'HeadMarker',
      netRegex: { id: ['01ED', '01EE'] },
      condition: Conditions.targetIsYou(),
      run: (data, matches) => data.lalaMyRotate = matches.id === '01ED' ? 'cw' : 'ccw',
    },
    {
      id: 'AAIS Lala Player 3과5',
      type: 'GainsEffect',
      // E89 = Times Three
      // ECE = Times Five
      netRegex: { effectId: ['E89', 'ECE'], source: 'Lala' },
      condition: Conditions.targetIsYou(),
      run: (data, matches) => data.lalaMyCount = matches.effectId === 'E89' ? 3 : 5,
    },
    {
      id: 'AAIS LaLa Arcane Blight 방향',
      type: 'StartsUsing',
      netRegex: { id: ['8BE2', '8BE3', '8BE4', '8BE5]'], source: 'Lala' },
      run: (data, matches) => {
        const blightMap: { [count: string]: MarchDirection } = {
          '8BE2': 'back',
          '8BE3': 'front',
          '8BE4': 'right',
          '8BE5': 'left',
        } as const;
        data.lalaBlight = blightMap[matches.id.toUpperCase()] ?? 'unknown';
      },
    },
    {
      id: 'AAIS Lala Arcane Blight',
      type: 'StartsUsing',
      netRegex: { id: '8BE6', source: 'Lala', capture: false },
      delaySeconds: 1,
      alertText: (data, _matches, output) => {
        if (data.lalaBlight === 'unknown')
          return output.text!();
        if (data.lalaRotate === 'unknown')
          return output[data.lalaBlight]!();
        if (isReverseRotate(data.lalaRotate, data.lalaCount)) {
          return {
            'front': output.left!(),
            'back': output.right!(),
            'left': output.back!(),
            'right': output.front!(),
            'unknown': output.text!(),
          }[data.lalaBlight];
        }
        return {
          'front': output.right!(),
          'back': output.left!(),
          'left': output.front!(),
          'right': output.back!(),
          'unknown': output.text!(),
        }[data.lalaBlight];
      },
      outputStrings: {
        text: '빈 곳으로~',
        front: Outputs.goFront,
        back: Outputs.getBehind,
        left: Outputs.left,
        right: Outputs.right,
      },
    },
    {
      id: 'AAIS Lala Analysis Unseen',
      type: 'GainsEffect',
      netRegex: { effectId: ['E8E', 'E8F', 'E90', 'E91'], source: 'Lala' },
      condition: Conditions.targetIsYou(),
      run: (data, matches) => {
        const unseenMap: { [count: string]: MarchDirection } = {
          'E8E': 'front',
          'E8F': 'back',
          'E90': 'right',
          'E91': 'left',
        } as const;
        data.lalaMyMarch = unseenMap[matches.effectId] ?? 'unknown';
      },
    },
    {
      id: 'AAIS Lala Arcane Array',
      type: 'Ability',
      netRegex: { id: '8BE7', source: 'Lala', capture: false },
      durationSeconds: 15,
      infoText: (data, _matches, output) => {
        const unseen = output[data.lalaMyMarch]!();
        return output.orbs!({ unseen: unseen });
      },
      outputStrings: {
        orbs: '뚤린 곳: ${unseen}',
        front: '앞',
        back: '뒤',
        left: '왼쪽',
        right: '오른쪽',
        unknown: Outputs.unknown,
      },
    },
    {
      id: 'AAIS Lala Targeted Light!',
      type: 'StartsUsing',
      netRegex: { id: '8CE1', source: 'Lala' },
      condition: Conditions.targetIsYou(),
      alertText: (data, _matches, output) => {
        if (data.lalaMyMarch === 'unknown')
          return output.text!();
        if (data.lalaMyRotate === 'unknown')
          return output[data.lalaMyMarch]!();
        if (isReverseRotate(data.lalaMyRotate, data.lalaMyCount))
          return {
            'front': output.left!(),
            'back': output.right!(),
            'left': output.back!(),
            'right': output.front!(),
          }[data.lalaMyMarch];
        return {
          'front': output.right!(),
          'back': output.left!(),
          'left': output.front!(),
          'right': output.back!(),
        }[data.lalaMyMarch];
      },
      outputStrings: {
        front: '보스 봐요',
        back: '뒤돌아 봐요',
        left: '오른쪽 봐요',
        right: '왼쪽 봐요',
        text: '열린 곳을 보스로',
      },
    },
    {
      id: 'AAIS Lala Strategic Strike',
      type: 'StartsUsing',
      netRegex: { id: '8C04', source: 'Lala' },
      response: Responses.tankBuster(),
    },
    {
      id: 'AAIS Lala Subtractive Suppressor Alpha',
      type: 'GainsEffect',
      netRegex: { effectId: 'E8C', source: 'Lala' },
      run: (data, matches) => {
        if (data.me === matches.target)
          data.lalaSubtractive = parseInt(matches.count);
        data.gainList.push(matches);
      },
    },
    {
      id: 'AAIS Lala Subtractive Suppressor Beta',
      type: 'GainsEffect',
      netRegex: { effectId: 'E8D', source: 'Lala' },
      condition: Conditions.targetIsYou(),
      run: (data, matches) => data.lalaSubtractive = parseInt(matches.count),
    },
    {
      id: 'AAIS Lala Surge Vector',
      type: 'GainsEffect',
      netRegex: { effectId: 'E8B', source: 'Lala' },
      run: (data, matches) => data.gainList.push(matches),
    },
    {
      id: 'AAIS Lala Planar Tactics',
      type: 'Ability',
      netRegex: { id: '8BEF', source: 'Lala', capture: false },
      delaySeconds: 1.2,
      durationSeconds: 10,
      infoText: (data, _matches, output) => {
        if (data.lalaSubtractive === undefined)
          return;

        const list = data.gainList;
        const [s1, s2] = list.filter((x) => x.effectId === 'E8B').map((x) => x.target);
        let issame;
        if (s1 === undefined || s2 === undefined)
          issame = false;
        else {
          const dps1 = data.party.isDPS(s1);
          const dps2 = data.party.isDPS(s2);
          issame = (dps1 && dps2) || (!dps1 && !dps2);
        }

        const mysub = data.lalaSubtractive;
        if (mysub === 1) {
          if (issame)
            return output.no1in!();
          const [pair] = list.filter((x) => parseInt(x.count) === 3);
          const name = pair === undefined ? output.unknown!() : data.party.member(pair.target).ajob;
          return output.no1out!({ name: name });
        }
        if (mysub === 2) {
          if (issame)
            return output.no2out!();
          const [pair] = list.filter((x) => parseInt(x.count) === 2 && x.target !== data.me);
          const name = pair === undefined ? output.unknown!() : data.party.member(pair.target).ajob;
          return output.no2in!({ name: name });
        }
        if (mysub === 3) {
          if (issame)
            return output.no3right!();
          const [pair] = list.filter((x) => parseInt(x.count) === 1);
          const name = pair === undefined ? output.unknown!() : data.party.member(pair.target).ajob;
          return output.no3left!({ name: name });
        }
      },
      run: (data) => data.gainList = [],
      outputStrings: {
        no1out: '[1/바깥] 3번과 페어: ${name}',
        no1in: '[1/안쪽] 2번과 페어',
        no2out: '[2/바깥] 1,3번과 페어',
        no2in: '[2/안쪽] 2번과 페어: ${name}',
        no3left: '[3/아래줄 왼쪽] 1번과 페어: ${name}',
        no3right: '[3/아래줄 오른쪽] 2번과 페어',
        unknown: Outputs.unknown,
      },
    },
    {
      id: 'AAIS Lala March',
      type: 'GainsEffect',
      netRegex: { effectId: ['E83', 'E84', 'E85', 'E86'], source: 'Lala' },
      condition: Conditions.targetIsYou(),
      delaySeconds: (_data, matches) => parseFloat(matches.duration) - 7,
      durationSeconds: 7,
      alertText: (data, matches, output) => {
        const map = {
          'E83': 'front',
          'E84': 'back',
          'E85': 'left',
          'E86': 'right',
        }[matches.effectId];
        if (map === undefined)
          return;
        if (data.lalaMyRotate === 'unknown')
          return output[map]!();
        if (isReverseRotate(data.lalaMyRotate, data.lalaMyCount)) {
          return {
            'front': output.left!(),
            'back': output.right!(),
            'left': output.back!(),
            'right': output.front!(),
          }[map];
        }
        return {
          'front': output.right!(),
          'back': output.left!(),
          'left': output.front!(),
          'right': output.back!(),
        }[map];
      },
      outputStrings: {
        text: '강제이동',
        front: '강제이동: 앞으로',
        back: '강제이동: 뒤로',
        left: '강제이동: 왼쪽',
        right: '강제이동: 오른쪽',
      },
    },
    {
      id: 'AAIS Lala Spatial Tactics',
      type: 'Ability',
      netRegex: { id: '8BF7', source: 'Lala', capture: false },
      delaySeconds: 1.2,
      durationSeconds: 20,
      infoText: (data, _matches, output) => {
        if (data.lalaSubtractive === undefined)
          return;
        return output[`no${data.lalaSubtractive}`]!();
      },
      outputStrings: {
        no1: '[1] 구슬 쪽 => 다 피해욧',
        no2: '[2] 구슬 쪽 => 한번 맞아요',
        no3: '[3] 구슬 없는쪽 => 두번 맞아요',
        no4: '[4] 구슬 없는쪽 => 세번 맞아요',
      },
    },
    {
      id: 'AAIS Lala Symmetric Surge Partner',
      type: 'Ability',
      netRegex: { id: '8BF8', source: 'Lala', capture: false },
      delaySeconds: 1.2,
      alertText: (data, _matches, output) => {
        const [s1, s2] = data.gainList.filter((x) => x.effectId === 'E8B').map((x) => x.target);
        if (s1 === undefined || s2 === undefined)
          return;

        const dps1 = data.party.isDPS(s1);
        const dps2 = data.party.isDPS(s2);
        const same = (dps1 && dps2) || (!dps1 && !dps2);
        if (same)
          return;

        if (data.role === 'dps')
          return output.swap!();
      },
      outputStrings: {
        swap: 'DPS 자리 바꿔요!',
      },
    },
    {
      id: 'AAIS Lala Symmetric Surge',
      type: 'Ability',
      netRegex: { id: '8BF8', source: 'Lala', capture: false },
      delaySeconds: 31,
      durationSeconds: 5,
      response: Responses.pairStack(),
      run: (data) => data.gainList = [],
    },
    {
      id: 'AAIS Lala Arcane Plot',
      type: 'StartsUsing',
      netRegex: { id: '8BF9', source: 'Lala', capture: false },
      infoText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: '바깥쪽 쫄 있는 곳이 북쪽!',
      },
    },
    {
      id: 'AAIS Lala Arcane Plot Spread',
      type: 'GainsEffect',
      netRegex: { effectId: 'B7D', source: 'Lala' },
      condition: (data, matches) =>
        data.me === matches.target && parseFloat(matches.duration) > 1.5,
      response: Responses.spread('alert'),
    },
    // ---------------- statice ----------------
    {
      id: 'AAIS Statice Aero IV',
      type: 'StartsUsing',
      netRegex: { id: '8966', source: 'Statice', capture: false },
      response: Responses.aoe('alert'),
    },
    {
      id: 'AAIS Statice Trick Reload',
      type: 'StartsUsing',
      netRegex: { id: '8967', source: 'Statice', capture: false },
      run: (data) => {
        data.stcReloadCount = 0;
        data.stcReloadFailed = 0;
      },
    },
    {
      id: 'AAIS Statice Locked and Loaded',
      type: 'Ability',
      netRegex: { id: '8925', source: 'Statice', capture: false },
      preRun: (data) => {
        if (data.stcReloadCount === 0)
          data.isStackFirst = false;
        data.stcReloadCount++;
      },
      infoText: (data, _matches, output) => {
        if (data.stcReloadCount === 1)
          return output.spread!();
      },
      outputStrings: {
        spread: '(먼저 흩어져요)',
      },
    },
    {
      id: 'AAIS Statice Misload',
      type: 'Ability',
      netRegex: { id: '8926', source: 'Statice', capture: false },
      preRun: (data) => {
        if (data.stcReloadCount === 0)
          data.isStackFirst = true;
        if (data.stcReloadCount < 7)
          data.stcReloadFailed = data.stcReloadCount;
        data.stcReloadCount++;
      },
      infoText: (data, _matches, output) => {
        if (data.stcReloadCount === 1)
          return output.stacks!();
        if (data.stcReloadCount < 8) {
          const mark = diceToMarker(data.stcReloadFailed);
          return output.text!({ safe: data.stcReloadFailed, mark: mark });
        }
      },
      outputStrings: {
        text: '(안전: ${safe}번${mark})',
        stacks: '(먼저 뭉쳐요)',
      },
    },
    {
      id: 'AAIS Statice Trapshooting 1',
      type: 'StartsUsing',
      netRegex: { id: '8D1C', source: 'Statice', capture: false },
      alertText: (data, _matches, output) => {
        const prev = data.isStackFirst;
        data.isStackFirst = !data.isStackFirst;
        if (prev)
          return output.stack!();
        return output.spread!();
      },
      outputStrings: {
        stack: Outputs.getTogether,
        spread: Outputs.spread,
      },
    },
    {
      id: 'AAIS Statice Trapshooting 2',
      type: 'StartsUsing',
      netRegex: { id: '8976', source: 'Statice', capture: false },
      alertText: (data, _matches, output) => {
        let ret;
        if (data.stcMyDuration < 10)
          ret = data.isStackFirst ? output.stack!() : output.spread!();
        else if (data.stcMyDuration < 20)
          ret = forceMove(output, data.stcMyMarch, data.isStackFirst);
        else if (data.stcMyDuration > 50)
          ret = forceMove(output, data.stcMyMarch, data.isStackFirst);
        else
          ret = data.isStackFirst ? output.stack!() : output.spread!();
        data.isStackFirst = !data.isStackFirst;
        return ret;
      },
      run: (data) => data.stcMyDuration = 0,
      outputStrings: {
        ...ForceMoveStrings,
      },
    },
    {
      id: 'AAIS Statice Trigger Happy',
      type: 'StartsUsing',
      netRegex: { id: '8968', source: 'Statice', capture: false },
      infoText: (data, _matches, output) => {
        const mark = diceToMarker(data.stcReloadFailed);
        return output.text!({ safe: data.stcReloadFailed, mark: mark });
      },
      outputStrings: {
        text: '안전: ${safe}번${mark}',
      },
    },
    {
      id: 'AAIS Statice Ring a Ring o\' Explosions',
      type: 'StartsUsing',
      netRegex: { id: '8979', source: 'Statice', capture: false },
      durationSeconds: 8,
      response: (data, _matches, output) => {
        // cactbot-builtin-response
        output.responseOutputStrings = {
          first: {
            en: '폭탄 피해요!',
          },
          second: {
            en: '폭탄 위치 기억! 빙글빙글!',
          },
          third: {
            en: '폭탄없는 안전한 곳 찾아요!',
          },
          fourth: {
            en: '${safe}번${mark} 쪽 안전한 곳으로! 도넛 조심!',
          },
          forthMove: {
            en: '${safe}번${mark}',
          },
          ...ForceMoveStrings,
        };
        data.stcRingRing++;
        if (data.stcRingRing === 1)
          return { infoText: output.first!() };
        if (data.stcRingRing === 2)
          return { infoText: output.second!() };
        if (data.stcRingRing === 3)
          return { infoText: output.third!() };
        if (data.stcRingRing === 4) {
          const mark = diceToMarker(data.stcReloadFailed);
          const fourth = output.fourth!({ safe: data.stcReloadFailed, mark: mark });
          if (data.stcMyDuration > 39 && data.stcMyDuration < 50) {
            const aim = output.forthMove!({ safe: data.stcReloadFailed, mark: mark });
            const move = forceMove(output, data.stcMyMarch, undefined, aim);
            return { infoText: fourth, alertText: move };
          }
          return { infoText: fourth };
        }
      },
    },
    {
      id: 'AAIS Statice Dartboard of Dancing Explosives',
      type: 'Ability',
      netRegex: { id: '8CC0', source: 'Statice', capture: false },
      infoText: (_data, _matches, output) => output.text!(),
      run: (data) => data.gainList = [],
      outputStrings: {
        text: '폭탄 피해서 안전한 곳으로',
      },
    },
    {
      id: 'AAIS Statice Bull\'s-eye Collect',
      type: 'GainsEffect',
      netRegex: { effectId: 'E9E' },
      run: (data, matches) => data.stcBullsEyes.push(data.party.member(matches.target)),
    },
    {
      id: 'AAIS Statice Bull\'s-eye 1',
      type: 'GainsEffect',
      netRegex: { effectId: 'E9E' },
      condition: (data) => !data.stcSeenPinwheeling,
      delaySeconds: (_data, matches) => parseFloat(matches.duration) - 5,
      suppressSeconds: 1,
      infoText: (data, _matches, output) => {
        if (data.role === 'tank')
          return output.blue!();
        if (data.role === 'healer')
          return output.yellow!();

        const dps = data.stcBullsEyes.filter((x) => x.role === 'dps');
        if (dps.length === 1)
          return output.red!();

        const other = dps[0]?.name !== data.me ? dps[0]?.name : dps[1]?.name;
        if (other === undefined)
          return output.red!();

        const mi = data.party.ajobId(data.me);
        const oi = data.party.ajobId(other);
        if (mi === undefined || oi === undefined || mi < oi)
          return output.red!();

        const roles = data.stcBullsEyes.map((x) => x.role);
        if (roles.includes('healer'))
          return output.blue!();
        return output.yellow!();
      },
      run: (data) => data.stcBullsEyes = [],
      outputStrings: {
        blue: '🟦파랑 밟아요',
        yellow: '🟨노랑 밟아요',
        red: '🟥빨강 밟아요',
      },
    },
    {
      id: 'AAIS Statice Beguiling Glitter',
      type: 'Ability',
      netRegex: { id: '8980', source: 'Statice', capture: false },
      condition: (data) => data.stcPop < 2,
      delaySeconds: 3,
      suppressSeconds: 1,
      alertText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: '넉백! 저항하라!!!',
        },
      },
    },
    {
      id: 'AAIS Statice Beguiling Glitter In/Out',
      type: 'Ability',
      netRegex: { id: '8980', source: 'Statice', capture: false },
      condition: (data) => data.stcPop < 2,
      delaySeconds: 8.5,
      durationSeconds: 8,
      suppressSeconds: 1,
      infoText: (data, _matches, output) => {
        if (data.isStackFirst)
          return output.out!();
        return output.in!();
      },
      outputStrings: {
        in: '한가운데 => 바깥에서 흩어져요',
        out: '바깥 => 한가운데서 뭉쳐요',
      },
    },
    {
      id: 'AAIS Statice Pop',
      type: 'StartsUsing',
      netRegex: { id: '896B', source: 'Statice', capture: false },
      run: (data) => data.stcPop++,
    },
    {
      id: 'AAIS Statice March',
      type: 'GainsEffect',
      netRegex: { effectId: ['DD2', 'DD3', 'DD4', 'DD5'] },
      condition: Conditions.targetIsYou(),
      run: (data, matches) => {
        const marchMap: { [count: string]: MarchDirection } = {
          'DD2': 'front',
          'DD3': 'back',
          'DD4': 'left',
          'DD5': 'right',
        } as const;
        data.stcMyMarch = marchMap[matches.effectId.toUpperCase()] ?? 'unknown';
        data.stcMyDuration = parseFloat(matches.duration);
      },
    },
    {
      id: 'AAIS Statice Surprising Claw Collect',
      type: 'Tether',
      netRegex: { id: '0011', source: 'Surprising Claw' },
      run: (data, matches) => data.stcClaws.push(matches.target),
    },
    {
      id: 'AAIS Statice Surprising Claw',
      type: 'Tether',
      netRegex: { id: '0011', source: 'Surprising Claw', capture: false },
      delaySeconds: 0.5,
      infoText: (data, _matches, output) => {
        if (!data.stcClaws.includes(data.me))
          return;
        let partner = undefined;
        if (data.stcClaws.length === 2)
          partner = data.stcClaws[0] !== data.me
            ? data.party.member(data.stcClaws[0]).ajob
            : data.party.member(data.stcClaws[1]).ajob;
        if (partner === undefined)
          partner = output.unknown!();
        return output.text!({ partner: partner });
      },
      run: (data) => data.stcClaws = [],
      outputStrings: {
        text: '내게 데스 손톱이! (${partner})',
        unknown: Outputs.unknown,
      },
    },
    {
      id: 'AAIS Statice Surprising Missile Collect',
      type: 'Tether',
      netRegex: { id: '0011', source: 'Surprising Missile' },
      run: (data, matches) => data.stcMissiles.push(matches.target),
    },
    {
      id: 'AAIS Statice Surprising Missile',
      type: 'Tether',
      netRegex: { id: '0011', source: 'Surprising Missile', capture: false },
      delaySeconds: 0.5,
      infoText: (data, _matches, output) => {
        if (!data.stcMissiles.includes(data.me))
          return;
        let partner = undefined;
        if (data.stcMissiles.length === 2)
          partner = data.stcMissiles[0] !== data.me
            ? data.party.member(data.stcMissiles[0]).ajob
            : data.party.member(data.stcMissiles[1]).ajob;
        if (partner === undefined)
          partner = output.unknown!();
        return output.text!({ partner: partner });
      },
      run: (data) => data.stcMissiles = [],
      outputStrings: {
        text: '미사일 + 체인, 한가운데로! (${partner})',
        unknown: Outputs.unknown,
      },
    },
    {
      id: 'AAIS Statice Shocking Abandon',
      type: 'StartsUsing',
      netRegex: { id: '8965', source: 'Statice' },
      response: Responses.tankBuster(),
    },
    {
      id: 'AAIS Statice Pinwheeling Dartboard',
      type: 'Ability',
      netRegex: { id: '8CBF', source: 'Statice', capture: false },
      infoText: (_data, _matches, output) => output.text!(),
      run: (data) => data.stcSeenPinwheeling = true,
      outputStrings: {
        text: '꼭지점 찾고 => 한가운데로',
      },
    },
    {
      id: 'AAIS Statice Ball of Fire',
      type: 'AddedCombatant',
      netRegex: { npcNameId: '12511' }, // 동글
      infoText: (data, matches, output) => {
        data.stcBallFire = stcBallOfFire(matches);
        if (data.stcBallFire > 1000)
          return output.text!({ mesg: `${data.stcBallFire}/${matches.heading}` });
      },
      outputStrings: {
        text: '후: ${mesg}',
      },
    },
    {
      id: 'AAIS Statice Bull\'s-eye 2',
      type: 'GainsEffect',
      netRegex: { effectId: 'E9E', capture: false },
      condition: (data) => data.stcSeenPinwheeling,
      delaySeconds: 1,
      suppressSeconds: 1,
      run: (data) => {
        const roles = data.stcBullsEyes.map((x) => x.role);
        data.stcBullsEyes = [];
        const dps = roles.filter((x) => x === 'dps');
        if (dps.length === 2) {
          data.stcAdjustBullsEye = true;
          return;
        }
        const th = roles.filter((x) => x === 'tank' || x === 'healer');
        if (th.length === 2) {
          data.stcAdjustBullsEye = true;
          return;
        }
        data.stcAdjustBullsEye = false;
      },
    },
    {
      id: 'AAIS Statice Burning Chains Collect',
      type: 'HeadMarker',
      netRegex: { id: '0061' },
      run: (data, matches) => data.stcChains.push(matches.target),
    },
    {
      id: 'AAIS Statice Burning Chains Alert',
      type: 'HeadMarker',
      netRegex: { id: '0061' },
      condition: Conditions.targetIsYou(),
      delaySeconds: 0.1,
      alertText: (data, _matches, output) => {
        if (data.stcChains.length !== 2)
          return output.chain!();
        const partner = data.stcChains[0] !== data.me ? data.stcChains[0] : data.stcChains[1];
        return output.chainWith!({ partner: data.party.member(partner).ajob });
      },
      outputStrings: {
        chain: '내게 체인!',
        chainWith: '내게 체인! (${partner})',
      },
    },
    {
      id: 'AAIS Statice Burning Chains Tether',
      type: 'Tether',
      netRegex: { id: '0009' },
      response: (data, matches, output) => {
        // cactbot-builtin-response
        output.responseOutputStrings = {
          cutchain: {
            en: '체인 끊어요!',
          },
          deathclaw: {
            en: '데스 손톱 유도 => 뭉쳐요',
          },
          adjustbullseye: {
            en: '북으로! 자리 조정 페어!',
          },
          bullseye: {
            en: '북으로! 페어',
          },
        };
        if (data.me === matches.source || data.me === matches.target)
          return { alarmText: output.cutchain!() };
        if (data.stcSeenPinwheeling) {
          if (data.stcAdjustBullsEye)
            return { alertText: output.adjustbullseye!() };
          return { infoText: output.bullseye!() };
        }
        return { alertText: output.deathclaw!() }; // 이건 데스 손톱 밖에 없다
      },
      run: (data) => data.stcChains = [],
    },
    // ---------------------------------------------- 테스트
    /*
    {
      id: 'AAIS marker test',
      type: 'HeadMarker',
      netRegex: {},
      infoText: (_data, matches, output) => {
        const tested: string[] = [
          '0017', // 흩어져요
          '003E', // 뭉쳐요
          '0061', // 체인
          '00A1', // 뭉쳐 대상에게 옴
          '00C6', // 쫄이 씀. 따라오는 머시기
          '00DC', // 체인 끊김? 아무튼 Burning Chains 다음 나옴
          '00E5', // 흩어져/뭉쳐/매직업 셋중 하나일거 같음...
          '0150', // 케투 1번 휩쓸림
          '0151', // 케투 2번
          '01E4', // 라라 보스 시계
          '01E5', // 라라 보스 반시계
          '01ED', // 라라 플레이어 시계
          '01EE', // 라라 플레이어 반시계
          '01F7', // 라라 플레이어 모르겟다. 방향 관련 같은데
          '01F8', // 라라 플레이어 모르겟다. 방향 관련 같은데
          '00F3', // 라라 버스터 Strategic Strike
          '0186', // 186~18B 주사위 모양
          '0187',
          '0188',
          '0189',
          '018A',
          '018B',
          '015B', // 스타 페어. 기믹 처리하면서 해결됨
          '00DA', // 스타 버스터 Socking Abandon
          '009C', // 스타 Ball of Fire. 문제의 이거 어디 있는지만 알면...
        ];
        if (tested.includes(matches.id))
          return;
        return output.text!({ id: matches.id, dest: matches.target });
      },
      outputStrings: {
        text: '헤드마커: ${id} (${dest})',
      },
    },
    */
  ],
  timelineReplace: [
    {
      locale: 'en',
      replaceText: {
        'Hydrobullet/Hydrofall': 'Hydrobullet/fall',
        'Hydrofall/Hydrobullet': 'Hydrofall/bullet',
        'Locked and Loaded/Misload': '탄알 장전',
        'Receding Twintides/Encroaching Twintides': 'Receding/Encroaching Twintides',
        'Far Tide/Near Tide': 'Far/Near Tide',
      },
    },
    {
      'locale': 'ja',
      'missingTranslations': true,
      'replaceSync': {
        'Aloalo Islekeeper': 'アロアロ・キーパー',
        'Aloalo Kiwakin': 'アロアロ・キワキン',
        'Aloalo Monk': 'アロアロ・モンク',
        'Aloalo Ray': 'アロアロ・ストライプレイ',
        'Aloalo Snipper': 'アロアロ・スニッパー',
        'Aloalo Wood Golem': 'アロアロ・ウッドゴーレム',
        'Ketuduke': 'ケトゥドゥケ',
        'Lala': 'ララ',
        'Spring Crystal': '湧水のクリスタル',
        'Statice': 'スターチス',
        'Surprising Claw': 'サプライズ・クロー',
        'Surprising Missile': 'サプライズ・ミサイル',
        'The Dawn Trial': 'ディルムの試練',
        'The Dusk Trial': 'クルペの試練',
        'The Midnight Trial': 'ノコセロの試練',
      },
    },
  ],
};

export default triggerSet;
