// This file was autogenerated from running ts-node util/sync_files.ts.
// DO NOT EDIT THIS FILE DIRECTLY.

import AutumnOopsy from '../../../../../resources/autumnoopsy';
import ZoneId from '../../../../../resources/zone_id';
import { OopsyData } from '../../../../../types/data';
import { OopsyTriggerSet } from '../../../../../types/oopsy';

export type Data = OopsyData;

const triggerSet: OopsyTriggerSet<Data> = {
  zoneId: ZoneId.AnotherAloaloIslandSavage,
  damageWarn: {
    // Trash 1
    'AAIS Twister': '8BC0', // Twister tornados
    'AAIS Kiwakin Tail Screw': '8BC9', // baited circle
    'AAIS Snipper Bubble Shower': '8BCA', // front conal
    'AAIS Snipper Crab Dribble': '8BCB', // fast back conal after Bubble Shower
    'AAIS Ray Hydrocannon': '8C4B', // line aoe
    'AAIS Ray Expulsion': '8BCE', // "get out"
    'AAIS Ray Electric Whorl': '8BCD', // "get in"

    // Ketuduke
    'AAIS Spring Crystal Saturate 1': '8ADB', // orb circle
    'AAIS Spring Crystal Saturate 2': '8ADC', // rupee line laser
    'AAIS Sphere Shatter': '8AE0', // moving arches
    'AAIS Receding Twintides': '8AE7', // initial out during out->in
    'AAIS Near Tide': '8AE8', // second out during in->out with 8AE9 Encroaching Twintides
    'AAIS Encroaching Twintides': '8AE9', // initial in during in->out
    'AAIS Far Tide': '8AEA', // second in during out->in with 8AE7 Receding Twintides
    'AAIS Hydrobomb': '8AEB', // 3x puddles duruing 8ABD Blowing Bubbles

    // Trash 2
    'AAIS Wood Golem Ovation': '8BD4', // front line aoe
    'AAIS Islekeeper Isle Drop': '8C3C', // front circle

    // Lala
    'AAIS Arcane Blight': '8BE6', // 270 degree rotating cleave
    'AAIS Bright Pulse 1': '8BE8', // initial blue square
    'AAIS Bright Pulse 2': '8BE9', // moving blue square
    'AAIS Arcane Mine': '8BF1', // initial Arcane Mine squares
    'AAIS Golem Aero II': '8BFB', // line damage from Aloalo Golem during Symmetric Surge
    'AAIS Telluric Theorem': '8C00', // puddles from Explosive Theorem spreads

    // Statice
    'AAIS Trigger Happy': '8969', // limit cut dart board
    'AAIS Bomb Burst': '897A', // bomb explosion
    'AAIS Uncommon Ground': '8CC2', // people who are on the same dartboard color with Bull's-eye
  },
  damageFail: {
    'AAIS Big Burst': '8AE3', // tower failure damage
    'AAIS Massive Explosion 1': '889C', // failing to resolve Subractive Suppressor Alpha
    'AAIS Massive Explosion 2': '889D', // failing to resolve Subractive Suppressor Beta
  },
  gainsEffectFail: {
    // C03 = 9999 duration, ??? = 15s duration
    'AAIS Dropsy': 'C03', // standing outside Ketuduke
    // C05 = 9999 duration, C06 = 15s duration
    'AAIS Bleeding': 'C05', // standing in blue square during Lala
    // BF9 = 9999 duration, BFA??? = 15s duration
    'AAIS Burns': 'BF9', // standing outside Lala
  },
  shareWarn: {
    'AAIS Hydrobullet': '8ADF', // spread debuffs
    'AAIS Wood Golem Tornado': '8BD3', // headmarker -> bind and heavy aoe
    'AAIS Powerful Light': '8BFD', // spread marker during Symmetric Surge that turns squares blue
    'AAIS Explosive Theorem': '8BFF', // large spreads with Telluric Theorem puddles
    'AAIS Trapshooting Spread': '8978', // spread damage from Trick Reload
  },
  soloWarn: {
    'AAIS Snipper Water III': '8BCC', // Snipper stack marker
    'AAIS Islekeeper Gravity Force': '8C3A', // stack
    'AAIS Trapshooting Stack': '8977', // stack damage from Trick Reload
  },
  soloFail: {
    'AAIS Hydrofall': '8ADE', // partner stack debuffs
    'AAIS Symmetric Surge': '8BF5', // two person stack that gives magic vuln up
  },
  triggers: [
    AutumnOopsy.pushedIntoWall('AAIS Angry Seas', '8AE1'),
    AutumnOopsy.pushedIntoWall('AAIS Pop', '896B'),
    AutumnOopsy.nonzeroDamageMistake('AAIS Hundred Lashings', ['8AE5', '8AE6'], 'warn'),
  ],
};

export default triggerSet;
