// This file was autogenerated from running ts-node util/sync_files.ts.
// DO NOT EDIT THIS FILE DIRECTLY.

import NetRegexes from '../../../../../resources/netregexes';
import ZoneId from '../../../../../resources/zone_id';
import { OopsyData } from '../../../../../types/data';
import { OopsyMistakeType, OopsyTrigger, OopsyTriggerSet } from '../../../../../types/oopsy';

// TODO: people who missed their 8AE2 Burst tower

export type Data = OopsyData;

// TODO: we could probably move this helper to some oopsy util.
const nonzeroDamageMistake = (
  triggerId: string,
  abilityId: string | string[],
  type: OopsyMistakeType,
): OopsyTrigger<OopsyData> => {
  return {
    id: triggerId,
    type: 'Ability',
    netRegex: NetRegexes.ability({ id: abilityId }),
    condition: (data, matches) => data.DamageFromMatches(matches) > 0,
    mistake: (_data, matches) => {
      return {
        type: type,
        blame: matches.target,
        reportId: matches.targetId,
        text: matches.ability,
      };
    },
  };
};

const triggerSet: OopsyTriggerSet<Data> = {
  zoneId: ZoneId.AnotherAloaloIslandSavage,
  damageWarn: {
    // Trash 1
    'AAIS Twister': '8BC0', // Twister tornados
    'AAIS Kiwakin Tail Screw': '8BC9', // baited circle
    'AAIS Snipper Bubble Shower': '8BCA', // front conal
    'AAIS Snipper Crab Dribble': '8BCB', // fast back conal after Bubble Shower
    'AAIS Ray Hydrocannon': '8C4B', // line aoe
    'AAIS Ray Expulsion': '8BCE', // "get out"
    'AAIS Ray Electric Whorl': '8BCD', // "get in"

    // Ketuduke
    'AAIS Spring Crystal Saturate 1': '8ADB', // orb circle
    'AAIS Spring Crystal Saturate 2': '8ADC', // rupee line laser
    'AAIS Sphere Shatter': '8AE0', // moving arches
    'AAIS Receding Twintides': '8AE7', // initial out during out->in
    'AAIS Near Tide': '8AE8', // second out during in->out with 8AE9 Encroaching Twintides
    'AAIS Encroaching Twintides': '8AE9', // initial in during in->out
    'AAIS Far Tide': '8AEA', // second in during out->in with 8AE7 Receding Twintides
    'AAIS Hydrobomb': '8AEB', // 3x puddles duruing 8ABD Blowing Bubbles
  },
  damageFail: {
    'AAIS Big Burst': '8AE3', // tower failure damage
  },
  shareWarn: {
    'AAIS Hydrobullet': '8ADF', // spread debuffs
  },
  soloWarn: {
    'AAIS Snipper Water III': '8BCC', // Snipper stack marker
    'AAIS Hydrofall': '8ADE', // partner stack debuffs
  },
  triggers: [
    {
      // Getting knocked into a wall from the Angry Seas knockback
      id: 'AAIS Angry Seas Wall',
      type: 'Ability',
      netRegex: NetRegexes.ability({ id: '8AE1' }),
      deathReason: (_data, matches) => {
        return {
          id: matches.targetId,
          name: matches.target,
          text: {
            en: 'Pushed into wall',
            de: 'Rückstoß in die Wand',
            fr: 'Poussé(e) dans le mur',
            ja: '壁へノックバック',
            cn: '击退至墙',
            ko: '넉백',
          },
        };
      },
    },
    nonzeroDamageMistake('AAIS Hundred Lashings', ['8AE5', '8AE6'], 'warn'),
  ],
};

export default triggerSet;
