name: 커버리지 리포트

on:
  push:
    branches:
      - master
    paths:
      - 'resources/**'
      - 'ui/raidboss/**'
      - 'ui/oopsyraidsy/**'
      - 'util/**'
      - '.github/workflows/coverage-report.yml'
      - '.github/actions/setup-js-env/'
  pull_request:
    paths:
      - 'resources/**'
      - 'ui/raidboss/**'
      - 'ui/oopsyraidsy/**'
      - 'util/**'
      - '.github/workflows/coverage-report.yml'
      - '.github/actions/setup-js-env/'

jobs:
  postprocess:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-js-env

      - name: npm run coverage-report
        run: |
          npm run coverage-report
