name: 자동 라벨

on:
  pull_request_target:
    types: [ opened, synchronize ]

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # force to ci checkout master repo to avoid
          # unexpected PR code to be executed with out github token
          ref: master
      - uses: ./.github/actions/setup-js-env

      - name: Run Label Script
        run: |
          node .github/scripts/auto-label.cjs
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_NUMBER: ${{ github.event.number }}
