name: 검사-스크립트

on:
  push:
    branches:
      - master
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.cjs'
      - '**/*.mjs'
      - '**/*.json'
      - '.github/workflows/script-lint.yml'
      - '.github/actions/setup-js-env/'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-js-env

      - name: TypeScript checking
        run: |
          npm run tsc-no-emit

      - name: npm run lint
        run: |
          npm run lint
