name: 검사-테스트

on:
  push:
    branches:
      - master
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.py'
      - 'package*.json'
      - 'ui/raidboss/**'
      - '.github/workflows/test.yml'
      - '.github/workflows/test-sync-files.yml'
      - '.github/actions/setup-js-env/'
      - 'package.json'

jobs:
  syncfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-js-env

      - name: npm run sync-files
        run: |
          npm run sync-files
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-js-env

      - name: npm test
        run: |
          npm test
