name: 검사-버전

on:
  push:
    branches:
      - master
    paths:
      - 'plugin/**'
      - '.github/workflows/lint-version.yml'
      - 'package.json'
  pull_request:
    paths:
      - 'plugin/**'
      - '.github/workflows/lint-version.yml'
      - 'package.json'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-js-env

      - name: npm run validate-versions
        run: |
          npm run validate-versions
